/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\nim-0.17.2\lib -o C:\Users\takala\Desktop\nim\scraping\nimcache\stdlib_net.o C:\Users\takala\Desktop\nim\scraping\nimcache\stdlib_net.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include "winsock2.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ {
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val;
NIM_BOOL has;
};
typedef NU8 tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NU8 tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ {
NI fd;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NI32 lastError;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_STDCALL_PTR(int, tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) (NI s, void* buf, int len, int flags);
typedef N_STDCALL_PTR(int, tyProc_T129bsPZ4FvuSF4rGFSBKkg) (NI s, SOCKADDR* name, unsigned int namelen);
struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ {
int ai_flags;
int ai_family;
int ai_socktype;
int ai_protocol;
size_t ai_addrlen;
NCSTRING ai_canonname;
SOCKADDR* ai_addr;
tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai_next;
};
typedef N_STDCALL_PTR(void, tyProc_IV3cwg4tBg3JP8ITSKt7oQ) (tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai);
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef NI tyArray_75VaQRxRbTdlDDGKKq3HSA[24];
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, isNone_Q4RsUqhsTDIbkeIguPSpvA)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self);
N_NIMCALL(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg, unsafeGet_fdGmwO5YUOWb8OBjkhgjng)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self);
N_NIMCALL(NIM_BOOL, isSome_Q4RsUqhsTDIbkeIguPSpvA_2)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(NI, waitFor_YtTtvuLXica0xhhz34ENjQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NF* waited, NI timeout, NI size, NimStringDesc* funcName);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_bU6ho49aX9aZ5qCG1X0EzmCw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI, select_EWIewKQK7bC2BMs0GJHLsA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* readfd, NI timeout);
N_NIMCALL(NIM_BOOL, hasDataBuffered_D9aXQ6Vx48ilhfQ09coEZXAw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* s);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NI, select_eXjloAphe9a2xyF9bVEutDXA)(tySequence_qwqHTkRvwhrRyENtudHQ7g** readfds, NI timeout);
N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_NIMCALL(NI32, osLastError_9bdZBDTfBOjOcVVodbA2otw)(void);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
N_NIMCALL(NI, recv_dq9a0j6Kas9cDXuWFRyz74Pw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, void* data, NI size);
N_NIMCALL(NI, readIntoBuf_9ca63taRllakURjj8LXqwSA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NI32 flags);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI32, getSocketError_1SsM0rEbxF3iz3zbEigCPA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0);
N_NIMCALL(NIM_BOOL, isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI32 lastError);
N_NIMCALL(void, socketError_bqyxlP0eahlYVYzUbNoKYA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NI err, NIM_BOOL async, NI32 lastError);
N_NIMCALL(NI, peekChar_1Us2e5M6fDfOXh9c6b0fMdQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NIM_CHAR* c);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NOCONV(void*, alloc_sVm4rDImKK2ZDdylByayiA)(NI size);
N_NOCONV(void, dealloc_RCjNtRnHdRYntrcE7YtwWw)(void* p);
N_NIMCALL(NI, newNativeSocket_WULFLawkclq9cew9bKzcJn4w)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, newSocket_0Wo5VJBkuvOB5dgcB0Nh2g)(NI fd, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered);
static N_NIMCALL(void, Marker_tyRef_MkGXUPMSENeRDS7EppfLgA)(void* p, NI op);
N_NIMCALL(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ*, getAddrInfo_oJYXw9a6xiOxTxda6sTTRJg)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_NIMCALL(void, setBlocking_HDkmwGOArLmNmxp9c5tG9c9cw)(NI s, NIM_BOOL blocking);
N_NIMCALL(void, connectAsync_LWuILbkhekOtXysaxbl53w)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc* name, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg af);
N_NIMCALL(NI, selectWrite_Xl49alpuj6Qo9brq9cgUHYNlQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g** writefds, NI timeout);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NI, send_dq9a0j6Kas9cDXuWFRyz74Pw_2)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, void* data, NI size);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, close_gkrint1G7N0tDyL9b6wUJug)(NI socket_0);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NI, recv_F7REPfTBuVE9a2JiMh9bHrxA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, void* data, NI size, NI timeout);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, readLine_NBa8Z4ylhaAEbMvQUNpqBA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc** line, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI maxLength);
N_NIMCALL(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw, toSockType_zz9bxu9cRa00a9b6j4pehnFgQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, toKnownDomain_jd0bVhz4WnNZrlz52jLB6g)(int family);
TNimType NTI_4xio0cAXR7XG4pF9bVcpxEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_FsA9cqNuEA9c2lfCA9bcCRasw_;
TNimType NTI_bU6ho49aX9aZ5qCG1X0EzmCw_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
extern tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_129257_;
extern NI osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
TNimType NTI_aIhANOOoETolVz9cccNO9cRQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_QQGLPNVVwLhYjkngqAxXQQ_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg_;
extern TNimType NTI_NQT1bItGG2X9byGdrWX7ujw_;
extern TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg_;
TNimType NTI_MkGXUPMSENeRDS7EppfLgA_;
extern tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_129218_;
extern tyProc_IV3cwg4tBg3JP8ITSKt7oQ Dl_129358_;
extern tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_129282_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_6, "false ", 6);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_7, "bufLen", 6);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_8, "currPos", 7);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_11, "Call to \'", 9);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_12, "\' timed out.", 12);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_14, "", 0);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_15, "readLine", 8);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_16, "buffer", 6);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_20, "\015\012  chunk <= size - read ", 25);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_23, "No valid socket error code available", 36);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_25, "\015\012", 2);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_27, "skip", 4);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_30, "recv", 4);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_32, "avail <= size - read ", 21);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_34, "\015\012  not (fd == osInvalidSocket) ", 32);
TNimNode* NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[3];
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_37, "Call to \'connect\' timed out.", 28);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_38, "Could not send all data.", 24);
STRING_LITERAL(TM_XqsrSBxhOTPgLQ9cX4MmV4A_43, "Couldn\'t resolve address: ", 26);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(int, toOSFlags_OfxuUkOMe7cgSmyynuaSLQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg socketFlags) {
	int result;
	nimfr_("toOSFlags", "net.nim");
	result = (int)0;
	{
		tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg f;
		NI i;
		f = (tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg)0;
		nimln_(2112, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2113, "system.nim");
			while (1) {
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_5;
				if (!(i <= ((NI) 1))) goto LA3;
				nimln_(2114, "system.nim");
				{
					if (!((socketFlags &(1U<<((NU)(((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg)chckRange(i, ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 0), ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1))))&7U)))!=0)) goto LA6_;
					f = ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg)chckRange(i, ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 0), ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1)));
					{
						nimln_(197, "net.nim");
						switch (f) {
						case ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 0):
						{
							nimln_(199, "net.nim");
							result = (NI32)(result | ((NI32) 2));
						}
						break;
						case ((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1):
						{
							nimln_(200, "net.nim");
							goto LA8;
						}
						break;
						}
					} LA8: ;
				}
				LA6_: ;
				nimln_(2115, "system.nim");
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_5);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ)(tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI32 lastError) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("isDisconnectionError", "net.nim");
	result = (NIM_BOOL)0;
	nimln_(184, "net.nim");
	nimln_(187, "net.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((flags &(1U<<((NU)(((tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg) 1))&7U)))!=0);
	if (!(T1_)) goto LA2_;
	nimln_(188, "net.nim");
	T1_ = (lastError == ((NI) 10054) || lastError == ((NI) 10053) || lastError == ((NI) 10052) || lastError == ((NI) 10101) || lastError == ((NI) 64));
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_NIMCALL(int, toCInt_ne8KyyT0jskmnqTgYiJN4w)(tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ opt) {
	int result;
	nimfr_("toCInt", "net.nim");
	result = (int)0;
	nimln_(870, "net.nim");
	nimln_(871, "net.nim");
	switch (opt) {
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 0):
	{
		result = SO_ACCEPTCONN;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 1):
	{
		result = SO_BROADCAST;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 2):
	{
		result = SO_DEBUG;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 3):
	{
		result = SO_DONTROUTE;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 4):
	{
		result = SO_KEEPALIVE;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 5):
	{
		result = SO_OOBINLINE;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 6):
	{
		result = SO_REUSEADDR;
	}
	break;
	case ((tyEnum_SOBool_SDlZUtKctfhvUZ58547HWQ) 7):
	{
		result = SO_REUSEADDR;
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_bU6ho49aX9aZ5qCG1X0EzmCw)(void* p, NI op) {
	tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw* a;
	a = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NIM_BOOL, hasDataBuffered_D9aXQ6Vx48ilhfQ09coEZXAw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* s) {
	NIM_BOOL result;
	nimfr_("hasDataBuffered", "net.nim");
	result = (NIM_BOOL)0;
	nimln_(977, "net.nim");
	result = NIM_FALSE;
	nimln_(978, "net.nim");
	{
		NIM_BOOL T5_;
		if (!(*s).isBuffered) goto LA3_;
		nimln_(979, "net.nim");
		T5_ = (NIM_BOOL)0;
		if (!(((2 &(1U<<((NU)((*s).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
		T5_ = (((NI) 0) < (*s).isBufferedU.S1.bufLen);
		if (!(T5_)) goto LA6_;
		nimln_(378, "system.nim");
		nimln_(979, "net.nim");
		if (!(((2 &(1U<<((NU)((*s).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
		if (!(((2 &(1U<<((NU)((*s).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
		T5_ = !(((*s).isBufferedU.S1.currPos == (*s).isBufferedU.S1.bufLen));
		LA6_: ;
		result = T5_;
	}
	LA3_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, select_EWIewKQK7bC2BMs0GJHLsA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* readfd, NI timeout) {
	NI result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* fds;
	nimfr_("select", "net.nim");
{	result = (NI)0;
	nimln_(987, "net.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasDataBuffered_D9aXQ6Vx48ilhfQ09coEZXAw(readfd);
		if (!T3_) goto LA4_;
		nimln_(988, "net.nim");
		result = ((NI) 1);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(990, "net.nim");
	fds = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 1);
	fds->data[0] = (*readfd).fd;
	nimln_(991, "net.nim");
	result = select_eXjloAphe9a2xyF9bVEutDXA((&fds), timeout);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3534, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_NIMCALL(NI, waitFor_YtTtvuLXica0xhhz34ENjQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NF* waited, NI timeout, NI size, NimStringDesc* funcName) {
	NI result;
	nimfr_("waitFor", "net.nim");
{	result = (NI)0;
	nimln_(1073, "net.nim");
	result = ((NI) 1);
	nimln_(1074, "net.nim");
	{
		if (!(size <= ((NI) 0))) goto LA3_;
		{
			if (!NIM_TRUE) goto LA7_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_6));
		}
		LA7_: ;
	}
	LA3_: ;
	nimln_(1075, "net.nim");
	{
		if (!(timeout == ((NI) -1))) goto LA11_;
		result = size;
		goto BeforeRet_;
	}
	LA11_: ;
	nimln_(1076, "net.nim");
	{
		NIM_BOOL T15_;
		NIM_BOOL T16_;
		NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_9;
		T15_ = (NIM_BOOL)0;
		T16_ = (NIM_BOOL)0;
		T16_ = (*socket_0).isBuffered;
		if (!(T16_)) goto LA17_;
		nimln_(378, "system.nim");
		nimln_(1076, "net.nim");
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
		T16_ = !(((*socket_0).isBufferedU.S1.bufLen == ((NI) 0)));
		LA17_: ;
		T15_ = T16_;
		if (!(T15_)) goto LA18_;
		nimln_(378, "system.nim");
		nimln_(1076, "net.nim");
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
		T15_ = !(((*socket_0).isBufferedU.S1.bufLen == (*socket_0).isBufferedU.S1.currPos));
		LA18_: ;
		if (!T15_) goto LA19_;
		nimln_(1077, "net.nim");
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
		TM_XqsrSBxhOTPgLQ9cX4MmV4A_9 = subInt((*socket_0).isBufferedU.S1.bufLen, (*socket_0).isBufferedU.S1.currPos);
		result = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_9);
		nimln_(1078, "net.nim");
		result = ((result <= size) ? result : size);
	}
	goto LA13_;
	LA19_: ;
	{
		NF startTime;
		NI selRet;
		NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_13;
		NF T37_;
		nimln_(1080, "net.nim");
		{
			NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_10;
			tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw* e;
			NimStringDesc* T26_;
			TM_XqsrSBxhOTPgLQ9cX4MmV4A_10 = subInt(timeout, ((NI) (((NF)((*waited)) * (NF)(1.0000000000000000e+003)))));
			if (!((NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_10) < ((NI) 1))) goto LA24_;
			e = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*)0;
			nimln_(2702, "system.nim");
			e = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*) newObj((&NTI_bU6ho49aX9aZ5qCG1X0EzmCw_), sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw));
			(*e).Sup.Sup.m_type = (&NTI_FsA9cqNuEA9c2lfCA9bcCRasw_);
			nimln_(1081, "net.nim");
			T26_ = (NimStringDesc*)0;
			T26_ = rawNewString(funcName->Sup.len + 21);
appendString(T26_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_11));
appendString(T26_, funcName);
appendString(T26_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_12));
			asgnRefNoCycle((void**) (&(*e).Sup.message), T26_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
			nimln_(1081, "net.nim");
			raiseException((Exception*)e, "TimeoutError");
		}
		LA24_: ;
		nimln_(1092, "net.nim");
		startTime = ntepochTime();
		nimln_(1093, "net.nim");
		TM_XqsrSBxhOTPgLQ9cX4MmV4A_13 = subInt(timeout, ((NI) (((NF)((*waited)) * (NF)(1.0000000000000000e+003)))));
		selRet = select_EWIewKQK7bC2BMs0GJHLsA(socket_0, (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_13));
		nimln_(1094, "net.nim");
		{
			NI32 T31_;
			if (!(selRet < ((NI) 0))) goto LA29_;
			T31_ = (NI32)0;
			T31_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T31_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
		}
		LA29_: ;
		nimln_(1095, "net.nim");
		{
			tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw* e_2;
			NimStringDesc* T36_;
			nimln_(378, "system.nim");
			nimln_(1095, "net.nim");
			if (!!((selRet == ((NI) 1)))) goto LA34_;
			e_2 = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*)0;
			nimln_(2702, "system.nim");
			e_2 = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*) newObj((&NTI_bU6ho49aX9aZ5qCG1X0EzmCw_), sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw));
			(*e_2).Sup.Sup.m_type = (&NTI_FsA9cqNuEA9c2lfCA9bcCRasw_);
			nimln_(1096, "net.nim");
			T36_ = (NimStringDesc*)0;
			T36_ = rawNewString(funcName->Sup.len + 21);
appendString(T36_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_11));
appendString(T36_, funcName);
appendString(T36_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_12));
			asgnRefNoCycle((void**) (&(*e_2).Sup.message), T36_);
			nimln_(2697, "system.nim");
			asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
			nimln_(1096, "net.nim");
			raiseException((Exception*)e_2, "TimeoutError");
		}
		LA34_: ;
		nimln_(1097, "net.nim");
		T37_ = (NF)0;
		T37_ = ntepochTime();
		pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils(waited, ((NF)(T37_) - (NF)(startTime)));
	}
	LA13_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, readIntoBuf_9ca63taRllakURjj8LXqwSA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NI32 flags) {
	NI result;
	int T1_;
	nimfr_("readIntoBuf", "net.nim");
{	result = (NI)0;
	nimln_(994, "net.nim");
	result = ((NI) 0);
	nimln_(1001, "net.nim");
	if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_16));
	T1_ = (int)0;
	T1_ = Dl_129257_((*socket_0).fd, ((void*) ((*socket_0).isBufferedU.S1.buffer)), ((int) 4000), flags);
	result = ((NI) (T1_));
	nimln_(1002, "net.nim");
	{
		if (!(result < ((NI) 0))) goto LA4_;
		nimln_(1005, "net.nim");
		(*socket_0).lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
	}
	LA4_: ;
	nimln_(1006, "net.nim");
	{
		if (!(result <= ((NI) 0))) goto LA8_;
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
		nimln_(1007, "net.nim");
		(*socket_0).isBufferedU.S1.bufLen = ((NI) 0);
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
		nimln_(1008, "net.nim");
		(*socket_0).isBufferedU.S1.currPos = ((NI) 0);
		nimln_(1009, "net.nim");
		goto BeforeRet_;
	}
	LA8_: ;
	if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
	nimln_(1010, "net.nim");
	(*socket_0).isBufferedU.S1.bufLen = result;
	if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
	nimln_(1011, "net.nim");
	(*socket_0).isBufferedU.S1.currPos = ((NI) 0);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, recv_dq9a0j6Kas9cDXuWFRyz74Pw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, void* data, NI size) {
	NI result;
	nimfr_("recv", "net.nim");
{	result = (NI)0;
	nimln_(1026, "net.nim");
	{
		if (!(size == ((NI) 0))) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(1027, "net.nim");
	{
		NI read;
		if (!(*socket_0).isBuffered) goto LA7_;
		nimln_(1028, "net.nim");
		{
			NI res;
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
			if (!((*socket_0).isBufferedU.S1.bufLen == ((NI) 0))) goto LA11_;
			nimln_(1014, "net.nim");
			res = readIntoBuf_9ca63taRllakURjj8LXqwSA(socket_0, ((NI32) 0));
			nimln_(1029, "net.nim");
			{
				nimln_(1015, "net.nim");
				if (!(res <= ((NI) 0))) goto LA15_;
				nimln_(1016, "net.nim");
				{
					if (!NIM_FALSE) goto LA19_;
					nimln_(1017, "net.nim");
					nimln_(1029, "net.nim");
					result = ((NI) 0);
					goto BeforeRet_;
				}
				goto LA17_;
				LA19_: ;
				{
					nimln_(1019, "net.nim");
					result = res;
					goto BeforeRet_;
				}
				LA17_: ;
			}
			LA15_: ;
		}
		LA11_: ;
		nimln_(1031, "net.nim");
		read = ((NI) 0);
		{
			nimln_(1032, "net.nim");
			while (1) {
				NI chunk;
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_17;
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_18;
				NCSTRING d;
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_21;
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_22;
				if (!(read < size)) goto LA23;
				nimln_(1033, "net.nim");
				{
					NI res_2;
					if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
					if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
					if (!((*socket_0).isBufferedU.S1.bufLen <= (*socket_0).isBufferedU.S1.currPos)) goto LA26_;
					nimln_(1014, "net.nim");
					res_2 = readIntoBuf_9ca63taRllakURjj8LXqwSA(socket_0, ((NI32) 0));
					nimln_(1034, "net.nim");
					{
						nimln_(1015, "net.nim");
						if (!(res_2 <= ((NI) 0))) goto LA30_;
						nimln_(1016, "net.nim");
						{
							if (!(((NI) 0) < read)) goto LA34_;
							nimln_(1017, "net.nim");
							nimln_(1034, "net.nim");
							result = read;
							goto BeforeRet_;
						}
						goto LA32_;
						LA34_: ;
						{
							nimln_(1019, "net.nim");
							result = res_2;
							goto BeforeRet_;
						}
						LA32_: ;
					}
					LA30_: ;
				}
				LA26_: ;
				nimln_(1036, "net.nim");
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_17 = subInt((*socket_0).isBufferedU.S1.bufLen, (*socket_0).isBufferedU.S1.currPos);
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_18 = subInt(size, read);
				chunk = (((NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_17) <= (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_18)) ? (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_17) : (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_18));
				nimln_(1037, "net.nim");
				d = ((NCSTRING) (data));
				nimln_(1038, "net.nim");
				{
					NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_19;
					TM_XqsrSBxhOTPgLQ9cX4MmV4A_19 = subInt(size, read);
					if (!!((chunk <= (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_19)))) goto LA39_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_20));
				}
				LA39_: ;
				nimln_(1039, "net.nim");
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_16));
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
				if ((NU)((*socket_0).isBufferedU.S1.currPos) > (NU)(4000)) raiseIndexError();
				copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&d[read]))), ((void*) ((&(*socket_0).isBufferedU.S1.buffer[((*socket_0).isBufferedU.S1.currPos)- 0]))), ((NI)chckRange(chunk, ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln_(1040, "net.nim");
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_21 = addInt(read, chunk);
				read = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_21);
				nimln_(1041, "net.nim");
				if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_22 = addInt((*socket_0).isBufferedU.S1.currPos, chunk);
				(*socket_0).isBufferedU.S1.currPos = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_22);
			} LA23: ;
		}
		nimln_(1043, "net.nim");
		result = read;
	}
	goto LA5_;
	LA7_: ;
	{
		int T42_;
		nimln_(1060, "net.nim");
		T42_ = (int)0;
		T42_ = Dl_129257_((*socket_0).fd, data, ((int)chckRange(size, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0));
		result = ((NI) (T42_));
		nimln_(1061, "net.nim");
		{
			if (!(result < ((NI) 0))) goto LA45_;
			nimln_(1063, "net.nim");
			(*socket_0).lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		}
		LA45_: ;
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NI32, getSocketError_1SsM0rEbxF3iz3zbEigCPA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0) {
	NI32 result;
	nimfr_("getSocketError", "net.nim");
	result = (NI32)0;
	nimln_(643, "net.nim");
	result = osLastError_9bdZBDTfBOjOcVVodbA2otw();
	nimln_(644, "net.nim");
	{
		if (!(result == ((NI32) 0))) goto LA3_;
		nimln_(645, "net.nim");
		result = (*socket_0).lastError;
	}
	LA3_: ;
	nimln_(646, "net.nim");
	{
		if (!(result == ((NI32) 0))) goto LA7_;
		nimln_(647, "net.nim");
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(result, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_23));
	}
	LA7_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, socketError_bqyxlP0eahlYVYzUbNoKYA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NI err, NIM_BOOL async, NI32 lastError) {
	nimfr_("socketError", "net.nim");
{	nimln_(691, "net.nim");
	{
		NIM_BOOL T3_;
		NI32 lastE;
		T3_ = (NIM_BOOL)0;
		T3_ = (err == ((NI) -1));
		if (!(T3_)) goto LA4_;
		T3_ = NIM_TRUE;
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(692, "net.nim");
		{
			if (!(((NI) (lastError)) == ((NI) -1))) goto LA9_;
			lastE = getSocketError_1SsM0rEbxF3iz3zbEigCPA(socket_0);
		}
		goto LA7_;
		LA9_: ;
		{
			lastE = lastError;
		}
		LA7_: ;
		nimln_(693, "net.nim");
		{
			if (!async) goto LA14_;
			nimln_(695, "net.nim");
			{
				if (!(lastE == ((NI32) 10035))) goto LA18_;
				nimln_(696, "net.nim");
				goto BeforeRet_;
			}
			goto LA16_;
			LA18_: ;
			{
				nimln_(697, "net.nim");
				raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastE, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
			}
			LA16_: ;
		}
		goto LA12_;
		LA14_: ;
		{
			nimln_(702, "net.nim");
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastE, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
		}
		LA12_: ;
	}
	LA5_: ;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(NI, peekChar_1Us2e5M6fDfOXh9c6b0fMdQ)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NIM_CHAR* c) {
	NI result;
	nimfr_("peekChar", "net.nim");
	result = (NI)0;
	nimln_(1158, "net.nim");
	{
		if (!(*socket_0).isBuffered) goto LA3_;
		nimln_(1159, "net.nim");
		result = ((NI) 1);
		nimln_(1160, "net.nim");
		{
			NIM_BOOL T7_;
			NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_24;
			NI res;
			T7_ = (NIM_BOOL)0;
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
			T7_ = ((*socket_0).isBufferedU.S1.bufLen == ((NI) 0));
			if (T7_) goto LA8_;
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_7));
			TM_XqsrSBxhOTPgLQ9cX4MmV4A_24 = subInt((*socket_0).isBufferedU.S1.bufLen, ((NI) 1));
			if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
			T7_ = ((NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_24) < (*socket_0).isBufferedU.S1.currPos);
			LA8_: ;
			if (!T7_) goto LA9_;
			nimln_(1161, "net.nim");
			res = readIntoBuf_9ca63taRllakURjj8LXqwSA(socket_0, ((NI32) 0));
			nimln_(1162, "net.nim");
			{
				if (!(res <= ((NI) 0))) goto LA13_;
				nimln_(1163, "net.nim");
				result = res;
			}
			LA13_: ;
		}
		LA9_: ;
		nimln_(1165, "net.nim");
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_16));
		if (!(((2 &(1U<<((NU)((*socket_0).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
		if ((NU)((*socket_0).isBufferedU.S1.currPos) > (NU)(4000)) raiseIndexError();
		(*c) = (*socket_0).isBufferedU.S1.buffer[((*socket_0).isBufferedU.S1.currPos)- 0];
	}
	goto LA1_;
	LA3_: ;
	{
		int T16_;
		nimln_(1175, "net.nim");
		T16_ = (int)0;
		T16_ = Dl_129257_((*socket_0).fd, ((void*) (c)), ((int) 1), ((int) 2));
		result = ((NI) (T16_));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, readLine_NBa8Z4ylhaAEbMvQUNpqBA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc** line, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI maxLength) {
	NF waited;
	nimfr_("readLine", "net.nim");
{	nimln_(1207, "net.nim");
	waited = 0.0;
	nimln_(1209, "net.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln_(1210, "net.nim");
		while (1) {
			NIM_CHAR c;
			NI T3_;
			NI n;
			c = (NIM_CHAR)0;
			nimln_(1212, "net.nim");
			T3_ = (NI)0;
			T3_ = waitFor_YtTtvuLXica0xhhz34ENjQ(socket_0, (&waited), timeout, ((NI) 1), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_15));
			T3_;
			nimln_(1213, "net.nim");
			n = recv_dq9a0j6Kas9cDXuWFRyz74Pw(socket_0, ((void*) ((&c))), ((NI) 1));
			nimln_(1214, "net.nim");
			{
				NI32 lastError;
				if (!(n < ((NI) 0))) goto LA6_;
				nimln_(1203, "net.nim");
				lastError = getSocketError_1SsM0rEbxF3iz3zbEigCPA(socket_0);
				nimln_(1204, "net.nim");
				{
					NIM_BOOL T10_;
					T10_ = (NIM_BOOL)0;
					T10_ = isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ(flags, lastError);
					if (!T10_) goto LA11_;
					(*line) = setLengthStr((*line), ((NI) 0));
					goto BeforeRet_;
				}
				LA11_: ;
				nimln_(1205, "net.nim");
				socketError_bqyxlP0eahlYVYzUbNoKYA(socket_0, n, NIM_FALSE, lastError);
			}
			goto LA4_;
			LA6_: ;
			{
				nimln_(1215, "net.nim");
				if (!(n == ((NI) 0))) goto LA14_;
				(*line) = setLengthStr((*line), ((NI) 0));
				goto BeforeRet_;
			}
			goto LA4_;
			LA14_: ;
			LA4_: ;
			nimln_(1216, "net.nim");
			{
				NI T20_;
				if (!((NU8)(c) == (NU8)(13))) goto LA18_;
				nimln_(1217, "net.nim");
				T20_ = (NI)0;
				T20_ = waitFor_YtTtvuLXica0xhhz34ENjQ(socket_0, (&waited), timeout, ((NI) 1), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_15));
				T20_;
				nimln_(1218, "net.nim");
				n = peekChar_1Us2e5M6fDfOXh9c6b0fMdQ(socket_0, (&c));
				nimln_(1219, "net.nim");
				{
					NIM_BOOL T23_;
					NI T27_;
					T23_ = (NIM_BOOL)0;
					T23_ = (((NI) 0) < n);
					if (!(T23_)) goto LA24_;
					T23_ = ((NU8)(c) == (NU8)(10));
					LA24_: ;
					if (!T23_) goto LA25_;
					nimln_(1220, "net.nim");
					T27_ = (NI)0;
					T27_ = recv_dq9a0j6Kas9cDXuWFRyz74Pw(socket_0, ((void*) ((&c))), ((NI) 1));
					T27_;
				}
				goto LA21_;
				LA25_: ;
				{
					NI32 lastError_2;
					nimln_(1221, "net.nim");
					if (!(n <= ((NI) 0))) goto LA29_;
					nimln_(1203, "net.nim");
					lastError_2 = getSocketError_1SsM0rEbxF3iz3zbEigCPA(socket_0);
					nimln_(1204, "net.nim");
					{
						NIM_BOOL T33_;
						T33_ = (NIM_BOOL)0;
						T33_ = isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ(flags, lastError_2);
						if (!T33_) goto LA34_;
						(*line) = setLengthStr((*line), ((NI) 0));
						goto BeforeRet_;
					}
					LA34_: ;
					nimln_(1205, "net.nim");
					socketError_bqyxlP0eahlYVYzUbNoKYA(socket_0, n, NIM_FALSE, lastError_2);
				}
				goto LA21_;
				LA29_: ;
				LA21_: ;
				nimln_(1222, "net.nim");
				{
					nimln_(1199, "net.nim");
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA38_;
					nimln_(1200, "net.nim");
					(*line) = resizeString((*line), 2);
appendString((*line), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_25));
				}
				LA38_: ;
				nimln_(1223, "net.nim");
				goto BeforeRet_;
			}
			goto LA16_;
			LA18_: ;
			{
				nimln_(1224, "net.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA41_;
				nimln_(1225, "net.nim");
				{
					nimln_(1199, "net.nim");
					if (!(((*line) ? (*line)->Sup.len : 0) == ((NI) 0))) goto LA45_;
					nimln_(1200, "net.nim");
					(*line) = resizeString((*line), 2);
appendString((*line), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_25));
				}
				LA45_: ;
				nimln_(1226, "net.nim");
				goto BeforeRet_;
			}
			goto LA16_;
			LA41_: ;
			LA16_: ;
			nimln_(1227, "net.nim");
			(*line) = addChar((*line), c);
			nimln_(1230, "net.nim");
			{
				if (!(maxLength < ((*line) ? (*line)->Sup.len : 0))) goto LA49_;
				goto LA1;
			}
			LA49_: ;
		}
	} LA1: ;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, skip_oq6CPui2q49cODkGVsjxTTA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NI size, NI timeout) {
	NF waited;
	void* dummy;
	NI bytesSkipped;
	nimfr_("skip", "net.nim");
	nimln_(1290, "net.nim");
	waited = 0.0;
	nimln_(1291, "net.nim");
	dummy = alloc_sVm4rDImKK2ZDdylByayiA(((NI)chckRange(size, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(1292, "net.nim");
	bytesSkipped = ((NI) 0);
	{
		nimln_(1293, "net.nim");
		while (1) {
			NI avail;
			NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_26;
			NI T3_;
			NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_28;
			nimln_(378, "system.nim");
			nimln_(1293, "net.nim");
			if (!!((bytesSkipped == size))) goto LA2;
			nimln_(1294, "net.nim");
			TM_XqsrSBxhOTPgLQ9cX4MmV4A_26 = subInt(size, bytesSkipped);
			avail = waitFor_YtTtvuLXica0xhhz34ENjQ(socket_0, (&waited), timeout, (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_26), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_27));
			nimln_(1295, "net.nim");
			T3_ = (NI)0;
			T3_ = recv_dq9a0j6Kas9cDXuWFRyz74Pw(socket_0, dummy, avail);
			TM_XqsrSBxhOTPgLQ9cX4MmV4A_28 = addInt(bytesSkipped, T3_);
			bytesSkipped = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_28);
		} LA2: ;
	}
	nimln_(1296, "net.nim");
	dealloc_RCjNtRnHdRYntrcE7YtwWw(dummy);
	popFrame();
}

N_NIMCALL(NI, recv_F7REPfTBuVE9a2JiMh9bHrxA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, void* data, NI size, NI timeout) {
	NI result;
	NF waited;
	NI read;
	nimfr_("recv", "net.nim");
{	result = (NI)0;
	nimln_(1102, "net.nim");
	waited = 0.0;
	nimln_(1104, "net.nim");
	read = ((NI) 0);
	{
		nimln_(1105, "net.nim");
		while (1) {
			NI avail;
			NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_29;
			NCSTRING d;
			NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_33;
			if (!(read < size)) goto LA2;
			nimln_(1106, "net.nim");
			TM_XqsrSBxhOTPgLQ9cX4MmV4A_29 = subInt(size, read);
			avail = waitFor_YtTtvuLXica0xhhz34ENjQ(socket_0, (&waited), timeout, (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_29), ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_30));
			nimln_(1107, "net.nim");
			d = ((NCSTRING) (data));
			nimln_(1108, "net.nim");
			{
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_31;
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_31 = subInt(size, read);
				if (!!((avail <= (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_31)))) goto LA5_;
				failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_32));
			}
			LA5_: ;
			nimln_(1109, "net.nim");
			result = recv_dq9a0j6Kas9cDXuWFRyz74Pw(socket_0, ((void*) ((&d[read]))), avail);
			nimln_(1110, "net.nim");
			{
				if (!(result == ((NI) 0))) goto LA9_;
				goto LA1;
			}
			LA9_: ;
			nimln_(1111, "net.nim");
			{
				if (!(result < ((NI) 0))) goto LA13_;
				nimln_(1112, "net.nim");
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(1113, "net.nim");
			TM_XqsrSBxhOTPgLQ9cX4MmV4A_33 = addInt(read, result);
			read = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_33);
		} LA2: ;
	} LA1: ;
	nimln_(1115, "net.nim");
	result = read;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_MkGXUPMSENeRDS7EppfLgA)(void* p, NI op) {
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* a;
	NI T1_;
	a = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)p;
	switch ((*a).isBuffered) {
	case NIM_TRUE:
	T1_ = (NI)0;
	break;
	case NIM_FALSE:
	break;
	} 
}

N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, newSocket_0Wo5VJBkuvOB5dgcB0Nh2g)(NI fd, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered) {
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* result;
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* T5_;
	nimfr_("newSocket", "net.nim");
	result = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)0;
	nimln_(206, "net.nim");
	{
		if (!!(!((fd == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_34));
	}
	LA3_: ;
	nimln_(207, "net.nim");
	T5_ = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)0;
	T5_ = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*) newObj((&NTI_MkGXUPMSENeRDS7EppfLgA_), sizeof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ));
	(*T5_).fd = fd;
	(*T5_).isBuffered = buffered;
	(*T5_).domain = domain;
	(*T5_).sockType = sockType;
	(*T5_).protocol = protocol;
	result = T5_;
	nimln_(213, "net.nim");
	{
		if (!buffered) goto LA8_;
		if (!(((2 &(1U<<((NU)((*result).isBuffered)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_8));
		nimln_(214, "net.nim");
		(*result).isBufferedU.S1.currPos = ((NI) 0);
	}
	LA8_: ;
	popFrame();
	return result;
}

N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, newSocket_8Lrat9ciQTaGiwISp8ak13A)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered) {
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* result;
	NI fd;
	nimfr_("newSocket", "net.nim");
	result = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)0;
	nimln_(235, "net.nim");
	fd = newNativeSocket_WULFLawkclq9cew9bKzcJn4w(domain, sockType, protocol);
	nimln_(236, "net.nim");
	{
		NI32 T5_;
		if (!(fd == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w)) goto LA3_;
		nimln_(237, "net.nim");
		T5_ = (NI32)0;
		T5_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
	}
	LA3_: ;
	nimln_(238, "net.nim");
	result = newSocket_0Wo5VJBkuvOB5dgcB0Nh2g(fd, domain, sockType, protocol, buffered);
	popFrame();
	return result;
}

N_NIMCALL(void, connect_ywwltDdbsh7jlzk9crzvpTw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc* address, NU16 port) {
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* aiList;
	NIM_BOOL success;
	NI32 lastError;
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* it;
	nimfr_("connect", "net.nim");
	nimln_(1552, "net.nim");
	aiList = getAddrInfo_oJYXw9a6xiOxTxda6sTTRJg(address, port, (*socket_0).domain, ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1), ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6));
	nimln_(1554, "net.nim");
	success = NIM_FALSE;
	lastError = (NI32)0;
	nimln_(1556, "net.nim");
	it = aiList;
	{
		nimln_(1557, "net.nim");
		while (1) {
			nimln_(378, "system.nim");
			nimln_(1557, "net.nim");
			if (!!((it == NIM_NIL))) goto LA2;
			nimln_(1558, "net.nim");
			{
				int T5_;
				T5_ = (int)0;
				T5_ = Dl_129218_((*socket_0).fd, (*it).ai_addr, ((unsigned int) ((*it).ai_addrlen)));
				if (!(T5_ == ((NI32) 0))) goto LA6_;
				nimln_(1559, "net.nim");
				success = NIM_TRUE;
				nimln_(1560, "net.nim");
				goto LA1;
			}
			goto LA3_;
			LA6_: ;
			{
				nimln_(1561, "net.nim");
				lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			}
			LA3_: ;
			nimln_(1562, "net.nim");
			it = (*it).ai_next;
		} LA2: ;
	} LA1: ;
	nimln_(1564, "net.nim");
	Dl_129358_(aiList);
	nimln_(1565, "net.nim");
	{
		if (!!(success)) goto LA11_;
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastError, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
	}
	LA11_: ;
	popFrame();
}

N_NIMCALL(void, connectAsync_LWuILbkhekOtXysaxbl53w)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc* name, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg af) {
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* aiList;
	NIM_BOOL success;
	NI32 lastError;
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* it;
	nimfr_("connectAsync", "net.nim");
	nimln_(1588, "net.nim");
	aiList = getAddrInfo_oJYXw9a6xiOxTxda6sTTRJg(name, port, af, ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1), ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6));
	nimln_(1590, "net.nim");
	success = NIM_FALSE;
	lastError = (NI32)0;
	nimln_(1592, "net.nim");
	it = aiList;
	{
		nimln_(1593, "net.nim");
		while (1) {
			int ret;
			nimln_(378, "system.nim");
			nimln_(1593, "net.nim");
			if (!!((it == NIM_NIL))) goto LA2;
			nimln_(1594, "net.nim");
			ret = Dl_129218_((*socket_0).fd, (*it).ai_addr, ((unsigned int) ((*it).ai_addrlen)));
			nimln_(1595, "net.nim");
			{
				if (!(ret == ((NI32) 0))) goto LA5_;
				nimln_(1596, "net.nim");
				success = NIM_TRUE;
				nimln_(1597, "net.nim");
				goto LA1;
			}
			goto LA3_;
			LA5_: ;
			{
				nimln_(1599, "net.nim");
				lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
				nimln_(1602, "net.nim");
				{
					if (!(lastError == ((NI32) 10035))) goto LA10_;
					nimln_(1603, "net.nim");
					success = NIM_TRUE;
					nimln_(1604, "net.nim");
					goto LA1;
				}
				LA10_: ;
			}
			LA3_: ;
			nimln_(1610, "net.nim");
			it = (*it).ai_next;
		} LA2: ;
	} LA1: ;
	nimln_(1612, "net.nim");
	Dl_129358_(aiList);
	nimln_(1613, "net.nim");
	{
		if (!!(success)) goto LA14_;
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastError, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
	}
	LA14_: ;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(void, connect_7FRYH2HWtRh0WJrfmgibow)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc* address, NU16 port, NI timeout) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* s;
	nimfr_("connect", "net.nim");
	nimln_(1621, "net.nim");
	setBlocking_HDkmwGOArLmNmxp9c5tG9c9cw((*socket_0).fd, NIM_FALSE);
	nimln_(1623, "net.nim");
	connectAsync_LWuILbkhekOtXysaxbl53w(socket_0, address, port, (*socket_0).domain);
	nimln_(1624, "net.nim");
	s = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 1);
	s->data[0] = (*socket_0).fd;
	nimln_(1625, "net.nim");
	{
		NI T3_;
		tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw* e;
		NimStringDesc* T6_;
		nimln_(378, "system.nim");
		nimln_(1625, "net.nim");
		T3_ = (NI)0;
		T3_ = selectWrite_Xl49alpuj6Qo9brq9cgUHYNlQ((&s), timeout);
		if (!!((T3_ == ((NI) 1)))) goto LA4_;
		e = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*) newObj((&NTI_bU6ho49aX9aZ5qCG1X0EzmCw_), sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw));
		(*e).Sup.Sup.m_type = (&NTI_FsA9cqNuEA9c2lfCA9bcCRasw_);
		nimln_(1626, "net.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_37));
		if (T6_) nimGCunrefNoCycle(T6_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(1626, "net.nim");
		raiseException((Exception*)e, "TimeoutError");
	}
	goto LA1_;
	LA4_: ;
	{
	}
	LA1_: ;
	nimln_(1634, "net.nim");
	setBlocking_HDkmwGOArLmNmxp9c5tG9c9cw((*socket_0).fd, NIM_TRUE);
	popFrame();
}

N_NIMCALL(NI, send_dq9a0j6Kas9cDXuWFRyz74Pw_2)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, void* data, NI size) {
	NI result;
	int T1_;
	nimfr_("send", "net.nim");
	result = (NI)0;
	nimln_(1309, "net.nim");
	T1_ = (int)0;
	T1_ = Dl_129282_((*socket_0).fd, data, ((int)chckRange(size, ((int) (-2147483647 -1)), ((int) 2147483647))), ((NI32) 0));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

N_NIMCALL(void, send_TWAsSGigu3N0YFsLMDBDlw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc* data, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags) {
	NI sent;
	nimfr_("send", "net.nim");
{	nimln_(1318, "net.nim");
	sent = send_dq9a0j6Kas9cDXuWFRyz74Pw_2(socket_0, ((void*) (data->data)), (data ? data->Sup.len : 0));
	nimln_(1319, "net.nim");
	{
		NI32 lastError;
		if (!(sent < ((NI) 0))) goto LA3_;
		nimln_(1320, "net.nim");
		lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		nimln_(1321, "net.nim");
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ(flags, lastError);
			if (!T7_) goto LA8_;
			goto BeforeRet_;
		}
		LA8_: ;
		nimln_(1322, "net.nim");
		socketError_bqyxlP0eahlYVYzUbNoKYA(socket_0, ((NI) -1), NIM_FALSE, lastError);
	}
	LA3_: ;
	nimln_(1324, "net.nim");
	{
		NI32 T14_;
		nimln_(378, "system.nim");
		nimln_(1324, "net.nim");
		if (!!((sent == (data ? data->Sup.len : 0)))) goto LA12_;
		nimln_(1325, "net.nim");
		T14_ = (NI32)0;
		T14_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T14_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_38));
	}
	LA12_: ;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

N_NIMCALL(void, close_m8ZGsx59b0Zg6YRPSokkGzA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0) {
	TSafePoint TM_XqsrSBxhOTPgLQ9cX4MmV4A_39;
	nimfr_("close", "net.nim");
	nimln_(851, "net.nim");
	pushSafePoint(&TM_XqsrSBxhOTPgLQ9cX4MmV4A_39);
	TM_XqsrSBxhOTPgLQ9cX4MmV4A_39.status = setjmp(TM_XqsrSBxhOTPgLQ9cX4MmV4A_39.context);
	if (TM_XqsrSBxhOTPgLQ9cX4MmV4A_39.status == 0) {
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
	}
	{
		nimln_(867, "net.nim");
		close_gkrint1G7N0tDyL9b6wUJug((*socket_0).fd);
	}
	if (TM_XqsrSBxhOTPgLQ9cX4MmV4A_39.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(NI, recv_4Mjz0AqlqEUYEphqS0TxEA)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NimStringDesc** data, NI size, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags) {
	NI result;
	nimfr_("recv", "net.nim");
{	result = (NI)0;
	nimln_(1132, "net.nim");
	(*data) = setLengthStr((*data), ((NI)chckRange(size, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(1133, "net.nim");
	result = recv_F7REPfTBuVE9a2JiMh9bHrxA(socket_0, ((void*) ((*data)->data)), size, timeout);
	nimln_(1134, "net.nim");
	{
		NI32 lastError;
		if (!(result < ((NI) 0))) goto LA3_;
		nimln_(1135, "net.nim");
		(*data) = setLengthStr((*data), ((NI) 0));
		nimln_(1136, "net.nim");
		lastError = getSocketError_1SsM0rEbxF3iz3zbEigCPA(socket_0);
		nimln_(1137, "net.nim");
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = isDisconnectionError_40p9aaw5rEmIprdUBGKsyYQ(flags, lastError);
			if (!T7_) goto LA8_;
			goto BeforeRet_;
		}
		LA8_: ;
		nimln_(1138, "net.nim");
		socketError_bqyxlP0eahlYVYzUbNoKYA(socket_0, result, NIM_FALSE, lastError);
	}
	LA3_: ;
	nimln_(1139, "net.nim");
	(*data) = setLengthStr((*data), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, recvLine_TyJtrtm9cDZ2r2fZhupS4bw)(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket_0, NI timeout, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags, NI maxLength) {
	NimStringDesc* result;
	nimfr_("recvLine", "net.nim");
	result = (NimStringDesc*)0;
	nimln_(1252, "net.nim");
	result = copyString(((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
	nimln_(1253, "net.nim");
	readLine_NBa8Z4ylhaAEbMvQUNpqBA(socket_0, (&result), timeout, flags, maxLength);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*, dial_ty9a9b08vt7aEg4gx4g3uheg)(NimStringDesc* address, NU16 port, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL buffered) {
	tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* result;
	tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* aiList;
	tyArray_75VaQRxRbTdlDDGKKq3HSA fdPerDomain;
	NIM_BOOL success;
	NI32 lastError;
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* it;
	tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
	NI lastFd;
	nimfr_("dial", "net.nim");
	result = (tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*)0;
	nimln_(1494, "net.nim");
	sockType = toSockType_zz9bxu9cRa00a9b6j4pehnFgQ(protocol);
	nimln_(1496, "net.nim");
	aiList = getAddrInfo_oJYXw9a6xiOxTxda6sTTRJg(address, port, ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0), sockType, protocol);
	memset((void*)fdPerDomain, 0, sizeof(fdPerDomain));
	{
		NI i;
		NI res;
		i = (NI)0;
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_40;
				if (!(res <= ((NI) 23))) goto LA3;
				nimln_(1988, "system.nim");
				i = ((NI)chckRange(res, ((NI) 0), ((NI) 23)));
				nimln_(1500, "net.nim");
				fdPerDomain[(i)- 0] = osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
				nimln_(1989, "system.nim");
				TM_XqsrSBxhOTPgLQ9cX4MmV4A_40 = addInt(res, ((NI) 1));
				res = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_40);
			} LA3: ;
		}
	}
	nimln_(1506, "net.nim");
	success = NIM_FALSE;
	lastError = (NI32)0;
	nimln_(1508, "net.nim");
	it = aiList;
	domain = (tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg)0;
	lastFd = (NI)0;
	{
		nimln_(1511, "net.nim");
		while (1) {
			nimln_(378, "system.nim");
			nimln_(1511, "net.nim");
			if (!!((it == NIM_NIL))) goto LA5;
			{
				tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ domainOpt;
				nimln_(1512, "net.nim");
				domainOpt = toKnownDomain_jd0bVhz4WnNZrlz52jLB6g((*it).ai_family);
				nimln_(1513, "net.nim");
				{
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = isNone_Q4RsUqhsTDIbkeIguPSpvA(domainOpt);
					if (!T9_) goto LA10_;
					nimln_(1514, "net.nim");
					it = (*it).ai_next;
					nimln_(1515, "net.nim");
					goto LA6;
				}
				LA10_: ;
				nimln_(1516, "net.nim");
				domain = unsafeGet_fdGmwO5YUOWb8OBjkhgjng(domainOpt);
				nimln_(1517, "net.nim");
				lastFd = fdPerDomain[(domain)- 0];
				nimln_(1518, "net.nim");
				{
					if (!(lastFd == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w)) goto LA14_;
					nimln_(1519, "net.nim");
					lastFd = newNativeSocket_WULFLawkclq9cew9bKzcJn4w(domain, sockType, protocol);
					nimln_(1520, "net.nim");
					{
						NI32 err;
						if (!(lastFd == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w)) goto LA18_;
						nimln_(1524, "net.nim");
						err = osLastError_9bdZBDTfBOjOcVVodbA2otw();
						nimln_(1525, "net.nim");
						Dl_129358_(aiList);
						{
							NI i_2;
							NI fd;
							NI i_3;
							i_2 = (NI)0;
							fd = (NI)0;
							nimln_(2159, "system.nim");
							i_3 = ((NI) 0);
							nimln_(2160, "system.nim");
							{
								if (!(((NI) (i_3)) <= ((NI) 23))) goto LA23_;
								{
									nimln_(2161, "system.nim");
									while (1) {
										NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_41;
										nimln_(2162, "system.nim");
										i_2 = i_3;
										fd = fdPerDomain[(i_3)- 0];
										nimln_(1503, "net.nim");
										{
											NIM_BOOL T29_;
											T29_ = (NIM_BOOL)0;
											nimln_(378, "system.nim");
											nimln_(1503, "net.nim");
											T29_ = !((fd == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w));
											if (!(T29_)) goto LA30_;
											nimln_(378, "system.nim");
											nimln_(1503, "net.nim");
											T29_ = !((((NI) (i_2)) == ((NI) -1)));
											LA30_: ;
											if (!T29_) goto LA31_;
											nimln_(1504, "net.nim");
											close_gkrint1G7N0tDyL9b6wUJug(fd);
										}
										LA31_: ;
										nimln_(2163, "system.nim");
										{
											if (!(((NI) 23) <= ((NI) (i_3)))) goto LA35_;
											goto LA25;
										}
										LA35_: ;
										nimln_(2164, "system.nim");
										TM_XqsrSBxhOTPgLQ9cX4MmV4A_41 = addInt(i_3, ((NI) 1));
										if (TM_XqsrSBxhOTPgLQ9cX4MmV4A_41 < 0 || TM_XqsrSBxhOTPgLQ9cX4MmV4A_41 > 23) raiseOverflow();
										i_3 = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_41);
									}
								} LA25: ;
							}
							LA23_: ;
						}
						nimln_(1527, "net.nim");
						raiseOSError_bEwAamo1N7TKcaU9akpiyIg(err, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
					}
					LA18_: ;
					nimln_(1528, "net.nim");
					fdPerDomain[(domain)- 0] = lastFd;
				}
				LA14_: ;
				nimln_(1529, "net.nim");
				{
					int T39_;
					T39_ = (int)0;
					T39_ = Dl_129218_(lastFd, (*it).ai_addr, ((unsigned int) ((*it).ai_addrlen)));
					if (!(T39_ == ((NI32) 0))) goto LA40_;
					nimln_(1530, "net.nim");
					success = NIM_TRUE;
					nimln_(1531, "net.nim");
					goto LA4;
				}
				LA40_: ;
				nimln_(1532, "net.nim");
				lastError = osLastError_9bdZBDTfBOjOcVVodbA2otw();
				nimln_(1533, "net.nim");
				it = (*it).ai_next;
			} LA6: ;
		} LA5: ;
	} LA4: ;
	nimln_(1534, "net.nim");
	Dl_129358_(aiList);
	{
		NI i_4;
		NI fd_2;
		NI i_5;
		i_4 = (NI)0;
		fd_2 = (NI)0;
		nimln_(2159, "system.nim");
		i_5 = ((NI) 0);
		nimln_(2160, "system.nim");
		{
			if (!(((NI) (i_5)) <= ((NI) 23))) goto LA45_;
			{
				nimln_(2161, "system.nim");
				while (1) {
					NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_42;
					nimln_(2162, "system.nim");
					i_4 = i_5;
					fd_2 = fdPerDomain[(i_5)- 0];
					nimln_(1503, "net.nim");
					{
						NIM_BOOL T51_;
						T51_ = (NIM_BOOL)0;
						nimln_(378, "system.nim");
						nimln_(1503, "net.nim");
						T51_ = !((fd_2 == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w));
						if (!(T51_)) goto LA52_;
						nimln_(378, "system.nim");
						nimln_(1503, "net.nim");
						nimln_(1535, "net.nim");
						T51_ = !((((NI) (i_4)) == ((NI) (domain))));
						LA52_: ;
						if (!T51_) goto LA53_;
						nimln_(1504, "net.nim");
						close_gkrint1G7N0tDyL9b6wUJug(fd_2);
					}
					LA53_: ;
					nimln_(2163, "system.nim");
					{
						if (!(((NI) 23) <= ((NI) (i_5)))) goto LA57_;
						goto LA47;
					}
					LA57_: ;
					nimln_(2164, "system.nim");
					TM_XqsrSBxhOTPgLQ9cX4MmV4A_42 = addInt(i_5, ((NI) 1));
					if (TM_XqsrSBxhOTPgLQ9cX4MmV4A_42 < 0 || TM_XqsrSBxhOTPgLQ9cX4MmV4A_42 > 23) raiseOverflow();
					i_5 = (NI)(TM_XqsrSBxhOTPgLQ9cX4MmV4A_42);
				}
			} LA47: ;
		}
		LA45_: ;
	}
	nimln_(1537, "net.nim");
	{
		if (!success) goto LA61_;
		nimln_(1538, "net.nim");
		result = newSocket_0Wo5VJBkuvOB5dgcB0Nh2g(lastFd, domain, sockType, protocol, NIM_TRUE);
	}
	goto LA59_;
	LA61_: ;
	{
		nimln_(378, "system.nim");
		nimln_(1539, "net.nim");
		if (!!((lastError == ((NI32) 0)))) goto LA64_;
		nimln_(1540, "net.nim");
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(lastError, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_14));
	}
	goto LA59_;
	LA64_: ;
	{
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
		NimStringDesc* T67_;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		nimln_(1542, "net.nim");
		T67_ = (NimStringDesc*)0;
		T67_ = rawNewString(address->Sup.len + 26);
appendString(T67_, ((NimStringDesc*) &TM_XqsrSBxhOTPgLQ9cX4MmV4A_43));
appendString(T67_, address);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T67_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(1542, "net.nim");
		raiseException((Exception*)e, "IOError");
	}
	LA59_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void) {
	nimfr_("net", "net.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void) {
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[2];
NI TM_XqsrSBxhOTPgLQ9cX4MmV4A_4;
static char* NIM_CONST TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[2] = {
"Peek", 
"SafeDisconn"};
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[6];
static TNimNode* TM_XqsrSBxhOTPgLQ9cX4MmV4A_36[3];
static TNimNode TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[16];
NTI_4xio0cAXR7XG4pF9bVcpxEg_.size = sizeof(tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg);
NTI_4xio0cAXR7XG4pF9bVcpxEg_.kind = 14;
NTI_4xio0cAXR7XG4pF9bVcpxEg_.base = 0;
NTI_4xio0cAXR7XG4pF9bVcpxEg_.flags = 3;
for (TM_XqsrSBxhOTPgLQ9cX4MmV4A_4 = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_4 < 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_4++) {
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].offset = TM_XqsrSBxhOTPgLQ9cX4MmV4A_4;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0].name = TM_XqsrSBxhOTPgLQ9cX4MmV4A_3[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[TM_XqsrSBxhOTPgLQ9cX4MmV4A_4+0];
}
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].len = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_2[0];
NTI_4xio0cAXR7XG4pF9bVcpxEg_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[2];
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.size = sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw);
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.kind = 17;
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].len = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3].kind = 2;
NTI_FsA9cqNuEA9c2lfCA9bcCRasw_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[3];
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.size = sizeof(tyObject_TimeoutError_FsA9cqNuEA9c2lfCA9bcCRasw*);
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.kind = 22;
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.base = (&NTI_FsA9cqNuEA9c2lfCA9bcCRasw_);
NTI_bU6ho49aX9aZ5qCG1X0EzmCw_.marker = Marker_tyRef_bU6ho49aX9aZ5qCG1X0EzmCw;
NTI_aIhANOOoETolVz9cccNO9cRQ_.size = sizeof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ);
NTI_aIhANOOoETolVz9cccNO9cRQ_.kind = 18;
NTI_aIhANOOoETolVz9cccNO9cRQ_.base = 0;
NTI_aIhANOOoETolVz9cccNO9cRQ_.flags = 3;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, fd);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[5].name = "fd";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].kind = 3;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBuffered);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].name = "isBuffered";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].sons = &NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[0];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[6].len = 2;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_36[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBufferedU.S1.buffer);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].typ = (&NTI_QQGLPNVVwLhYjkngqAxXQQ_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[8].name = "buffer";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_36[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBufferedU.S1.currPos);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[9].name = "currPos";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_36[2] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, isBufferedU.S1.bufLen);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[10].name = "bufLen";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].len = 3; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_36[0];
NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[1] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[7];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].len = 0; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11].kind = 2;
NimDT__aIhANOOoETolVz9cccNO9cRQ_isBuffered[0] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[11];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[2] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, lastError);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[12].name = "lastError";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[3] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[13];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[13].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[13].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, domain);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[13].typ = (&NTI_Q79bEtFARvq0ekDNtvj3Vqg_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[13].name = "domain";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[4] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[14];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[14].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[14].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, sockType);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[14].typ = (&NTI_NQT1bItGG2X9byGdrWX7ujw_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[14].name = "sockType";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[5] = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15];
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15].kind = 1;
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15].offset = offsetof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ, protocol);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15].typ = (&NTI_dqJ1OqRGclxIMMdSLRzzXg_);
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[15].name = "protocol";
TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].len = 6; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].kind = 2; TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4].sons = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_35[0];
NTI_aIhANOOoETolVz9cccNO9cRQ_.node = &TM_XqsrSBxhOTPgLQ9cX4MmV4A_0[4];
NTI_MkGXUPMSENeRDS7EppfLgA_.size = sizeof(tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ*);
NTI_MkGXUPMSENeRDS7EppfLgA_.kind = 22;
NTI_MkGXUPMSENeRDS7EppfLgA_.base = (&NTI_aIhANOOoETolVz9cccNO9cRQ_);
NTI_MkGXUPMSENeRDS7EppfLgA_.flags = 2;
NTI_MkGXUPMSENeRDS7EppfLgA_.marker = Marker_tyRef_MkGXUPMSENeRDS7EppfLgA;
}

