/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\nim-0.17.2\lib -o C:\Users\takala\Desktop\nim\scraping\nimcache\stdlib_nativesockets.o C:\Users\takala\Desktop\nim\scraping\nimcache\stdlib_nativesockets.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include "winsock2.h"
#include <string.h>
#include "ws2tcpip.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ;
typedef struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ;
typedef struct tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ;
typedef struct tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Hostent_azV1qb29cFIFe582aezrNAQ tyObject_Hostent_azV1qb29cFIFe582aezrNAQ;
typedef struct tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_J0FzjuY02DFObU1sQZLwJA tyTuple_J0FzjuY02DFObU1sQZLwJA;
typedef struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA;
typedef struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(int, tyProc_awTV7srwWeJ9cGPOCgBQa7g) (NI s, long cmd, long* argptr);
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ {
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val;
NIM_BOOL has;
};
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
typedef N_STDCALL_PTR(NI, tyProc_9aO2cP4IgwjXF8JfUR57CHQ) (int af, int typ, int protocol);
typedef N_STDCALL_PTR(int, tyProc_IQbFr9cLT9bipWCXYfwYwjOw) (NI s);
typedef N_STDCALL_PTR(int, tyProc_T129bsPZ4FvuSF4rGFSBKkg) (NI s, SOCKADDR* name, unsigned int namelen);
typedef N_STDCALL_PTR(int, tyProc_wy9bpl6t1mtPtDWeg0xLpDA) (NI s, int backlog);
struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ {
int ai_flags;
int ai_family;
int ai_socktype;
int ai_protocol;
size_t ai_addrlen;
NCSTRING ai_canonname;
SOCKADDR* ai_addr;
tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai_next;
};
typedef N_STDCALL_PTR(int, tyProc_MvjKU9c5nvs0N3IrS4vNgSw) (NCSTRING nodename, NCSTRING servname, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* hints, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ** res);
typedef N_STDCALL_PTR(void, tyProc_IV3cwg4tBg3JP8ITSKt7oQ) (tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai);
typedef N_STDCALL_PTR(tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA*, tyProc_E0SwAAX9bj9a9aV7n5MiMKzig) (NCSTRING name, NCSTRING proto);
struct tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ {
NimStringDesc* name;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* aliases;
NU16 port;
NimStringDesc* proto;
};
struct tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA {
NCSTRING s_name;
NCSTRING* s_aliases;
NCSTRING s_proto;
NI16 s_port;
};
typedef N_STDCALL_PTR(tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA*, tyProc_M3E1eZF9azJd5WrGSHMqEDA) (int port, NCSTRING proto);
typedef N_STDCALL_PTR(NU32, tyProc_jPIQsVcE09cbsdBUbAUxTCQ) (NCSTRING cp);
typedef N_STDCALL_PTR(tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, tyProc_oU4d9cTB9cxBBS1maSQYgLMA) (IN_ADDR* ip, unsigned int len, int theType);
struct tyObject_Hostent_azV1qb29cFIFe582aezrNAQ {
NimStringDesc* name;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* aliases;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg addrtype;
NI length;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* addrList;
};
struct tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw {
NCSTRING h_name;
NCSTRING* h_aliases;
NI16 h_addrtype;
NI16 h_length;
NCSTRING* h_addr_list;
};
typedef N_STDCALL_PTR(tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, tyProc_sUmKECsDIMWXpmy9a1Mqegg) (NCSTRING name);
typedef N_STDCALL_PTR(int, tyProc_7gdD6mJWQegUjarRikmB9bg) (NCSTRING hostname, int len);
typedef NIM_CHAR tyArray_Wfh9bjgBQ4UqJsyISUuDSuA[16];
typedef N_STDCALL_PTR(int, tyProc_VXEvL0NvawmzSZzsbIHW6Q) (NI s, SOCKADDR* name, unsigned int* namelen);
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
typedef N_STDCALL_PTR(NCSTRING, tyProc_MgrHyJlVVXQLRahsT9c14gQ) (IN_ADDR i);
typedef NIM_CHAR tyArray_1NlJ8ipZDU6GZ9bDFAyQjfQ[8];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyTuple_J0FzjuY02DFObU1sQZLwJA {
NimStringDesc* Field0;
NU16 Field1;
};
typedef NIM_CHAR tyArray_2cWMSJoP9cqN4yIK0ILkQaQ[64];
typedef N_STDCALL_PTR(int, tyProc_smMaEORdTTSo9bCzv0g049aQ) (NI s, int level, int optname, void* optval, unsigned int* optlen);
typedef N_STDCALL_PTR(int, tyProc_K6tJduk9ckQgneh7oD8F4Bg) (NI s, int level, int optname, void* optval, unsigned int optlen);
struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA {
NI32 tv_sec;
NI32 tv_usec;
};
typedef NI tyArray_SLBTEB08vk46ttuRaTxAYw[64];
struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog {
int fd_count;
tyArray_SLBTEB08vk46ttuRaTxAYw fd_array;
};
typedef N_STDCALL_PTR(int, tyProc_rWrG4X5lbcXQyLNkF9aNWhQ) (int nfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* readfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* writefds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* exceptfds, tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA* timeout);
typedef NIM_CHAR tyArray_EWK8XzFKXCg2WflN3ijhqA[257];
typedef NIM_CHAR tyArray_4249al09aeC68W9cvqMnjIYOA[129];
typedef N_STDCALL_PTR(int, tyProc_As5z9bYt859cLKWaorPRgQYA) (NI16 wVersionRequired, WSADATA* WSData);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, some_JMiA9ccATJp8JunIrSlndYA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val);
N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, none_IBO7fiOVpMVOmhrZWFqq1A)(void);
N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, toKnownDomain_jd0bVhz4WnNZrlz52jLB6g)(int family);
N_NIMCALL(int, toInt_8FqW9bXNjjJADB8XlKnpNLg)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ);
N_NIMCALL(int, toInt_9cDpnbeIxivYaLcJBJkQ2nQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p);
N_NIMCALL(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw, toSockType_zz9bxu9cRa00a9b6j4pehnFgQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_NIMCALL(NI, newNativeSocket_WULFLawkclq9cew9bKzcJn4w)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_NIMCALL(NI, newNativeSocket_3upU1a4YiumYk2g5YvqfSA)(int domain, int sockType, int protocol);
N_NIMCALL(void, close_gkrint1G7N0tDyL9b6wUJug)(NI socket_0);
N_NIMCALL(int, bindAddr_2tQ5L6urT7QbAhZLRP4TBA)(NI socket_0, SOCKADDR* name, unsigned int namelen);
N_NIMCALL(int, listen_x9cO0dJiBh5DSfILBu5u9caQ)(NI socket_0, int backlog);
N_NIMCALL(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ*, getAddrInfo_oJYXw9a6xiOxTxda6sTTRJg)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_NIMCALL(NI32, osLastError_9bdZBDTfBOjOcVVodbA2otw)(void);
N_NIMCALL(void, dealloc_CDSQIIFHQ4ElQ1Lt6BJuEg)(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai);
N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x);
N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x);
N_NIMCALL(void, getServByName_CbLPGzG25vLA69bCp9c8vUGg)(NimStringDesc* name, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg)(NCSTRING* a);
N_NIMCALL(void, getServByPort_ArkrSwAitAfuTL9a9cpcTIhQ)(NU16 port, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, getHostByAddr_thIyCshVWqmin8xsxY5Tvw)(NimStringDesc* ip, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result);
N_NIMCALL(void, getHostByName_GtLhLbA2rADAuSXSXBQ09aQ)(NimStringDesc* name, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result);
N_NIMCALL(NimStringDesc*, getHostname_9aXAlD9aED7aisSUkE4TsLaw)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg, getSockDomain_gCpH59bOpIMSgBk8rXR8mkg)(NI socket_0);
N_NIMCALL(NimStringDesc*, getAddrString_BdEpgs6VoOC9a7qLA4d9aCYQ)(SOCKADDR* sockAddr);
static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgsystem)(NCSTRING x, NCSTRING y);
N_STDCALL(NCSTRING, inet_ntop_LTipcLQ2Q4XlT8sQeiwC8A)(int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NU16, getSockName_vpdzNZNuSiYK8ffxz4poBQ)(NI socket_0);
N_NIMCALL(void, getLocalAddr_U7rY6ScGBPOrRGnI22ZKxw)(NI socket_0, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result);
N_NIMCALL(void, getPeerAddr_U7rY6ScGBPOrRGnI22ZKxw_2)(NI socket_0, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result);
N_NIMCALL(NI, getSockOptInt_Bcy79aVO5nZ0AND6B1KoG4g)(NI socket_0, NI level, NI optname);
N_NIMCALL(void, setSockOptInt_Q4lBY4MFWt3Wx9bU5oC8TvA)(NI socket_0, NI level, NI optname, NI optval);
N_NIMCALL(void, setBlocking_HDkmwGOArLmNmxp9c5tG9c9cw)(NI s, NIM_BOOL blocking);
N_NIMCALL(tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA, timeValFromMilliseconds_8n6ccdvLo6VgMVggcNy9bzw)(NI timeout);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, createFdSet_Uq0gtMrL5zwaOYtdZK68kg)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd, tySequence_qwqHTkRvwhrRyENtudHQ7g* s, NI* m);
N_NIMCALL(void, FD_ZERO_yeePfMmq9aNgPmxq9aV4wa4A)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s);
N_NIMCALL(void, FD_SET_RyfVGaM8zBlYSZOQ5CvEEQ)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(void, pruneSocketSet_70Zyypm1k20h9c9bjjAUrOmw)(tySequence_qwqHTkRvwhrRyENtudHQ7g** s, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd);
N_NIMCALL(int, FD_ISSET_NkjjeLx4p9b4GT29buKQYcxA)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* set);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
N_NIMCALL(NI, select_eXjloAphe9a2xyF9bVEutDXA)(tySequence_qwqHTkRvwhrRyENtudHQ7g** readfds, NI timeout);
N_NIMCALL(NI, selectRead_eXjloAphe9a2xyF9bVEutDXA_2)(tySequence_qwqHTkRvwhrRyENtudHQ7g** readfds, NI timeout);
N_NIMCALL(NI, selectWrite_Xl49alpuj6Qo9brq9cgUHYNlQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g** writefds, NI timeout);
NI osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
static void* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2;
tyProc_awTV7srwWeJ9cGPOCgBQa7g Dl_165863_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_9aO2cP4IgwjXF8JfUR57CHQ Dl_129197_;
extern tyProc_IQbFr9cLT9bipWCXYfwYwjOw Dl_129202_;
extern tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_129212_;
extern tyProc_wy9bpl6t1mtPtDWeg0xLpDA Dl_129253_;
extern tyProc_MvjKU9c5nvs0N3IrS4vNgSw Dl_129349_;
extern tyProc_IV3cwg4tBg3JP8ITSKt7oQ Dl_129358_;
extern tyProc_E0SwAAX9bj9a9aV7n5MiMKzig Dl_129172_;
extern tyProc_M3E1eZF9azJd5WrGSHMqEDA Dl_129177_;
extern tyProc_jPIQsVcE09cbsdBUbAUxTCQ Dl_129311_;
extern tyProc_oU4d9cTB9cxBBS1maSQYgLMA Dl_129182_;
extern tyProc_sUmKECsDIMWXpmy9a1Mqegg Dl_129189_;
extern tyProc_7gdD6mJWQegUjarRikmB9bg Dl_129193_;
extern tyProc_VXEvL0NvawmzSZzsbIHW6Q Dl_129224_;
extern tyProc_MgrHyJlVVXQLRahsT9c14gQ Dl_129362_;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_VXEvL0NvawmzSZzsbIHW6Q Dl_129231_;
extern tyProc_smMaEORdTTSo9bCzv0g049aQ Dl_129238_;
extern tyProc_K6tJduk9ckQgneh7oD8F4Bg Dl_129246_;
extern tyProc_rWrG4X5lbcXQyLNkF9aNWhQ Dl_129273_;
WSADATA wsa_ClAT9bhT9cqG9adztamb5X9b2w;
extern tyProc_As5z9bYt859cLKWaorPRgQYA Dl_129344_;
TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg_;
TNimType NTI_NQT1bItGG2X9byGdrWX7ujw_;
TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg_;
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4, "ws2_32.dll", 10);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5, "ws2_32.dll", 10);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8, "", 0);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9, "Service not found.", 18);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10, "unknown socket family in getSockFamily", 38);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11, "Unknown socket family in getAddrString", 38);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12, "invalid socket family in getLocalAddr", 37);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_18, "len(a) == L seq modified while iterating over it", 48);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain) {
	short result;
	nimfr_("toInt", "nativesockets.nim");
	result = (short)0;
	nimln_(162, "nativesockets.nim");
	result = ((NI16)(NU16)(NU)(((NI) (domain))));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, toKnownDomain_jd0bVhz4WnNZrlz52jLB6g)(int family) {
	tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ result;
	nimfr_("toKnownDomain", "nativesockets.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(167, "nativesockets.nim");
	{
		if (!(family == ((NI32) 0))) goto LA3_;
		result = some_JMiA9ccATJp8JunIrSlndYA(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(168, "nativesockets.nim");
		if (!(family == ((NI32) 2))) goto LA6_;
		result = some_JMiA9ccATJp8JunIrSlndYA(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(169, "nativesockets.nim");
		if (!(family == ((NI32) 23))) goto LA9_;
		result = some_JMiA9ccATJp8JunIrSlndYA(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23));
	}
	goto LA1_;
	LA9_: ;
	{
		nimln_(170, "nativesockets.nim");
		result = none_IBO7fiOVpMVOmhrZWFqq1A();
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(int, toInt_8FqW9bXNjjJADB8XlKnpNLg)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ) {
	int result;
	nimfr_("toInt", "nativesockets.nim");
	result = (int)0;
	nimln_(173, "nativesockets.nim");
	result = ((int) (typ));
	popFrame();
	return result;
}

N_NIMCALL(int, toInt_9cDpnbeIxivYaLcJBJkQ2nQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p) {
	int result;
	nimfr_("toInt", "nativesockets.nim");
	result = (int)0;
	nimln_(176, "nativesockets.nim");
	result = ((int) (p));
	popFrame();
	return result;
}

N_NIMCALL(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw, toSockType_zz9bxu9cRa00a9b6j4pehnFgQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw result;
	nimfr_("toSockType", "nativesockets.nim");
	result = (tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw)0;
	nimln_(179, "nativesockets.nim");
	switch (protocol) {
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6):
	{
		result = ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 17):
	{
		result = ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 2);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 18):
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 19):
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 20):
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 21):
	{
		result = ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 3);
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(NI, newNativeSocket_WULFLawkclq9cew9bKzcJn4w)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	NI result;
	short T1_;
	int T2_;
	int T3_;
	nimfr_("newNativeSocket", "nativesockets.nim");
	result = (NI)0;
	nimln_(190, "nativesockets.nim");
	nimln_(191, "nativesockets.nim");
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	T2_ = (int)0;
	T2_ = toInt_8FqW9bXNjjJADB8XlKnpNLg(sockType);
	T3_ = (int)0;
	T3_ = toInt_9cDpnbeIxivYaLcJBJkQ2nQ(protocol);
	result = Dl_129197_(((int) (T1_)), T2_, T3_);
	popFrame();
	return result;
}

N_NIMCALL(NI, newNativeSocket_3upU1a4YiumYk2g5YvqfSA)(int domain, int sockType, int protocol) {
	NI result;
	nimfr_("newNativeSocket", "nativesockets.nim");
	result = (NI)0;
	nimln_(195, "nativesockets.nim");
	nimln_(199, "nativesockets.nim");
	result = Dl_129197_(domain, sockType, protocol);
	popFrame();
	return result;
}

N_NIMCALL(void, close_gkrint1G7N0tDyL9b6wUJug)(NI socket_0) {
	int T1_;
	nimfr_("close", "nativesockets.nim");
	nimln_(204, "nativesockets.nim");
	T1_ = (int)0;
	T1_ = Dl_129202_(socket_0);
	T1_;
	popFrame();
}

N_NIMCALL(int, bindAddr_2tQ5L6urT7QbAhZLRP4TBA)(NI socket_0, SOCKADDR* name, unsigned int namelen) {
	int result;
	nimfr_("bindAddr", "nativesockets.nim");
	result = (int)0;
	nimln_(211, "nativesockets.nim");
	result = Dl_129212_(socket_0, name, namelen);
	popFrame();
	return result;
}

N_NIMCALL(int, listen_x9cO0dJiBh5DSfILBu5u9caQ)(NI socket_0, int backlog) {
	int result;
	nimfr_("listen", "nativesockets.nim");
	result = (int)0;
	nimln_(218, "nativesockets.nim");
	result = Dl_129253_(socket_0, backlog);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ*, getAddrInfo_oJYXw9a6xiOxTxda6sTTRJg)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* result;
	tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ hints;
	short T1_;
	int gaiResult;
	NimStringDesc* T6_;
	nimfr_("getAddrInfo", "nativesockets.nim");
	result = (tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ*)0;
	memset((void*)(&hints), 0, sizeof(hints));
	nimln_(229, "nativesockets.nim");
	result = NIM_NIL;
	nimln_(230, "nativesockets.nim");
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	hints.ai_family = ((int) (T1_));
	nimln_(231, "nativesockets.nim");
	hints.ai_socktype = toInt_8FqW9bXNjjJADB8XlKnpNLg(sockType);
	nimln_(232, "nativesockets.nim");
	hints.ai_protocol = toInt_9cDpnbeIxivYaLcJBJkQ2nQ(protocol);
	nimln_(237, "nativesockets.nim");
	{
		if (!(domain == ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23))) goto LA4_;
		nimln_(238, "nativesockets.nim");
		hints.ai_flags = ((int) 8);
	}
	LA4_: ;
	nimln_(239, "nativesockets.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = dollar__rzAI8EMyNBAQwGODeohhAA(port);
	gaiResult = Dl_129349_(address->data, T6_->data, (&hints), &result);
	nimln_(240, "nativesockets.nim");
	{
		NI32 T11_;
		nimln_(378, "system.nim");
		nimln_(240, "nativesockets.nim");
		if (!!((gaiResult == ((NI32) 0)))) goto LA9_;
		nimln_(242, "nativesockets.nim");
		T11_ = (NI32)0;
		T11_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T11_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA9_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, dealloc_CDSQIIFHQ4ElQ1Lt6BJuEg)(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai) {
	nimfr_("dealloc", "nativesockets.nim");
	nimln_(248, "nativesockets.nim");
	Dl_129358_(ai);
	popFrame();
}

N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x) {
	NU32 result;
	nimfr_("ntohl", "nativesockets.nim");
	result = (NU32)0;
	nimln_(256, "nativesockets.nim");
	nimln_(255, "nativesockets.nim");
	nimln_(256, "nativesockets.nim");
	nimln_(257, "nativesockets.nim");
	nimln_(258, "nativesockets.nim");
	result = (NU32)((NU32)((NU32)((NU32)((NU32)(x) >> (NU32)(((NU32) 24))) | (NU32)((NU32)((NU32)(x) >> (NU32)(((NU32) 8))) & ((NU32) 65280))) | (NU32)((NU32)((NU32)(x) << (NU32)(((NU32) 8))) & ((NU32) 16711680))) | (NU32)((NU32)(x) << (NU32)(((NU32) 24))));
	popFrame();
	return result;
}

N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x) {
	NU16 result;
	nimfr_("ntohs", "nativesockets.nim");
	result = (NU16)0;
	nimln_(274, "nativesockets.nim");
	result = (NU16)((NU16)((NU16)(x) >> (NU16)(((NU16) 8))) | (NU16)((NU16)(x) << (NU16)(((NU16) 8))));
	popFrame();
	return result;
}

N_NIMCALL(void, getServByName_CbLPGzG25vLA69bCp9c8vUGg)(NimStringDesc* name, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result) {
	tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA* s;
	nimfr_("getServByName", "nativesockets.nim");
	nimln_(322, "nativesockets.nim");
	s = Dl_129172_(name->data, proto->data);
	nimln_(325, "nativesockets.nim");
	{
		NI32 T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA3_: ;
	nimln_(326, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln_(327, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).s_aliases));
	nimln_(328, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln_(329, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, getServByPort_ArkrSwAitAfuTL9a9cpcTIhQ)(NU16 port, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result) {
	tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA* s;
	nimfr_("getServByPort", "nativesockets.nim");
	nimln_(338, "nativesockets.nim");
	s = Dl_129177_(((int)chckRange(((NI)(NU)(NU16)(((NI16)chckRange(port, ((NI16) -32768), ((NI16) 32767))))), ((int) (-2147483647 -1)), ((int) 2147483647))), proto->data);
	nimln_(341, "nativesockets.nim");
	{
		NI32 T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA3_: ;
	nimln_(342, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln_(343, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).s_aliases));
	nimln_(344, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln_(345, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

N_NIMCALL(void, getHostByAddr_thIyCshVWqmin8xsxY5Tvw)(NimStringDesc* ip, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result) {
	IN_ADDR myaddr;
	tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw* s;
	nimfr_("getHostByAddr", "nativesockets.nim");
	memset((void*)(&myaddr), 0, sizeof(myaddr));
	nimln_(350, "nativesockets.nim");
	myaddr.s_addr = Dl_129311_(ip->data);
	nimln_(353, "nativesockets.nim");
	s = Dl_129182_((&myaddr), ((unsigned int) (((NI)sizeof(IN_ADDR)))), ((int) 2));
	nimln_(355, "nativesockets.nim");
	{
		NI32 T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA3_: ;
	nimln_(367, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln_(368, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_aliases));
	nimln_(370, "nativesockets.nim");
	(*Result).addrtype = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg)chckRange((*s).h_addrtype, ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0), ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23)));
	nimln_(378, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrList), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_addr_list));
	nimln_(379, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_NIMCALL(void, getHostByName_GtLhLbA2rADAuSXSXBQ09aQ)(NimStringDesc* name, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result) {
	tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw* s;
	nimfr_("getHostByName", "nativesockets.nim");
	nimln_(384, "nativesockets.nim");
	s = Dl_129189_(name->data);
	nimln_(387, "nativesockets.nim");
	{
		NI32 T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA3_: ;
	nimln_(388, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln_(389, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_aliases));
	nimln_(391, "nativesockets.nim");
	(*Result).addrtype = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg)chckRange((*s).h_addrtype, ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0), ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23)));
	nimln_(399, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrList), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_addr_list));
	nimln_(400, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_NIMCALL(NimStringDesc*, getHostname_9aXAlD9aED7aisSUkE4TsLaw)(void) {
	NimStringDesc* result;
	int success;
	NI x;
	nimfr_("getHostname", "nativesockets.nim");
	result = (NimStringDesc*)0;
	nimln_(407, "nativesockets.nim");
	result = mnewString(((NI) 64));
	nimln_(409, "nativesockets.nim");
	success = Dl_129193_(result->data, ((int) 64));
	nimln_(413, "nativesockets.nim");
	{
		NI32 T5_;
		nimln_(378, "system.nim");
		nimln_(413, "nativesockets.nim");
		if (!!((success == ((int) 0)))) goto LA3_;
		nimln_(414, "nativesockets.nim");
		T5_ = (NI32)0;
		T5_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA3_: ;
	nimln_(415, "nativesockets.nim");
	x = (result->data ? strlen(result->data) : 0);
	nimln_(416, "nativesockets.nim");
	result = setLengthStr(result, ((NI)chckRange(x, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_NIMCALL(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg, getSockDomain_gCpH59bOpIMSgBk8rXR8mkg)(NI socket_0) {
	tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg result;
	SOCKADDR_IN6 name;
	unsigned int namelen;
	nimfr_("getSockDomain", "nativesockets.nim");
	result = (tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg)0;
	memset((void*)(&name), 0, sizeof(name));
	nimln_(421, "nativesockets.nim");
	namelen = ((unsigned int) (((NI)sizeof(SOCKADDR_IN6))));
	nimln_(422, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_129224_(socket_0, ((SOCKADDR*) ((&name))), (&namelen));
		if (!(T3_ == ((NI32) -1))) goto LA4_;
		nimln_(424, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4_: ;
	nimln_(425, "nativesockets.nim");
	{
		if (!(name.sin6_family == ((NI16) 2))) goto LA9_;
		nimln_(426, "nativesockets.nim");
		result = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2);
	}
	goto LA7_;
	LA9_: ;
	{
		nimln_(427, "nativesockets.nim");
		if (!(name.sin6_family == ((NI16) 23))) goto LA12_;
		nimln_(428, "nativesockets.nim");
		result = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23);
	}
	goto LA7_;
	LA12_: ;
	{
		NI32 T15_;
		nimln_(430, "nativesockets.nim");
		T15_ = (NI32)0;
		T15_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10));
	}
	LA7_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgsystem)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	nimfr_("==", "system.nim");
	result = (NIM_BOOL)0;
	nimln_(3849, "system.nim");
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(3850, "system.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		nimln_(3851, "system.nim");
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(NimStringDesc*, getAddrString_BdEpgs6VoOC9a7qLA4d9aCYQ)(SOCKADDR* sockAddr) {
	NimStringDesc* result;
	nimfr_("getAddrString", "nativesockets.nim");
	result = (NimStringDesc*)0;
	nimln_(435, "nativesockets.nim");
	{
		NCSTRING T5_;
		if (!((*sockAddr).sa_family == ((NI16) 2))) goto LA3_;
		nimln_(436, "nativesockets.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_129362_((*((SOCKADDR_IN*) (sockAddr))).sin_addr);
		result = cstrToNimstr(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		NI addrLen;
		IN6_ADDR* addr6;
		nimln_(437, "nativesockets.nim");
		if (!((*sockAddr).sa_family == ((NI16) 23))) goto LA7_;
		nimln_(438, "nativesockets.nim");
		addrLen = ((NI) 46);
		nimln_(440, "nativesockets.nim");
		result = mnewString(((NI)chckRange(addrLen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(441, "nativesockets.nim");
		addr6 = (&(*((SOCKADDR_IN6*) (sockAddr))).sin6_addr);
		nimln_(449, "nativesockets.nim");
		{
			NCSTRING T11_;
			NIM_BOOL T12_;
			NI32 T15_;
			if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
			nimln_(450, "nativesockets.nim");
			T11_ = (NCSTRING)0;
			T11_ = inet_ntop_LTipcLQ2Q4XlT8sQeiwC8A(((int) 23), ((void*) (addr6)), ((NCSTRING) ((&result->data[((NI) 0)]))), ((NI32)chckRange((result ? result->Sup.len : 0), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			T12_ = (NIM_BOOL)0;
			T12_ = eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgsystem(T11_, NIM_NIL);
			if (!T12_) goto LA13_;
			nimln_(451, "nativesockets.nim");
			T15_ = (NI32)0;
			T15_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA13_: ;
		nimln_(452, "nativesockets.nim");
		result = setLengthStr(result, ((NI)chckRange((result->data ? strlen(result->data) : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	goto LA1_;
	LA7_: ;
	{
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
		NimStringDesc* T17_;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		nimln_(454, "nativesockets.nim");
		T17_ = (NimStringDesc*)0;
		T17_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
		if (T17_) nimGCunrefNoCycle(T17_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(454, "nativesockets.nim");
		raiseException((Exception*)e, "IOError");
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(NU16, getSockName_vpdzNZNuSiYK8ffxz4poBQ)(NI socket_0) {
	NU16 result;
	SOCKADDR_IN name;
	unsigned int namelen;
	nimfr_("getSockName", "nativesockets.nim");
	result = (NU16)0;
	memset((void*)(&name), 0, sizeof(name));
	nimln_(460, "nativesockets.nim");
	name.sin_family = ((NI16) 2);
	nimln_(465, "nativesockets.nim");
	namelen = ((unsigned int) (((NI)sizeof(SOCKADDR_IN))));
	nimln_(466, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_129224_(socket_0, ((SOCKADDR*) ((&name))), (&namelen));
		if (!(T3_ == ((NI32) -1))) goto LA4_;
		nimln_(468, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4_: ;
	nimln_(469, "nativesockets.nim");
	result = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name.sin_port);
	popFrame();
	return result;
}

N_NIMCALL(void, getLocalAddr_U7rY6ScGBPOrRGnI22ZKxw)(NI socket_0, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result) {
	nimfr_("getLocalAddr", "nativesockets.nim");
	nimln_(475, "nativesockets.nim");
	switch (domain) {
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		SOCKADDR_IN name;
		unsigned int namelen;
		NCSTRING T8_;
		memset((void*)(&name), 0, sizeof(name));
		nimln_(479, "nativesockets.nim");
		name.sin_family = ((NI16) 2);
		nimln_(482, "nativesockets.nim");
		namelen = ((unsigned int) (((NI)sizeof(SOCKADDR_IN))));
		nimln_(483, "nativesockets.nim");
		{
			int T4_;
			NI32 T7_;
			T4_ = (int)0;
			T4_ = Dl_129224_(socket_0, ((SOCKADDR*) ((&name))), (&namelen));
			if (!(T4_ == ((NI32) -1))) goto LA5_;
			nimln_(485, "nativesockets.nim");
			T7_ = (NI32)0;
			T7_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T7_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA5_: ;
		nimln_(486, "nativesockets.nim");
		T8_ = (NCSTRING)0;
		T8_ = Dl_129362_(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(T8_));
		nimln_(487, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name.sin_port);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23):
	{
		SOCKADDR_IN6 name_2;
		unsigned int namelen_2;
		tyArray_2cWMSJoP9cqN4yIK0ILkQaQ buf;
		memset((void*)(&name_2), 0, sizeof(name_2));
		nimln_(491, "nativesockets.nim");
		name_2.sin6_family = ((NI16) 23);
		nimln_(494, "nativesockets.nim");
		namelen_2 = ((unsigned int) (((NI)sizeof(SOCKADDR_IN6))));
		nimln_(495, "nativesockets.nim");
		{
			int T12_;
			NI32 T15_;
			T12_ = (int)0;
			T12_ = Dl_129224_(socket_0, ((SOCKADDR*) ((&name_2))), (&namelen_2));
			if (!(T12_ == ((NI32) -1))) goto LA13_;
			nimln_(497, "nativesockets.nim");
			T15_ = (NI32)0;
			T15_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA13_: ;
		memset((void*)buf, 0, sizeof(buf));
		nimln_(500, "nativesockets.nim");
		{
			NCSTRING T18_;
			NI32 T21_;
			nimln_(501, "nativesockets.nim");
			T18_ = (NCSTRING)0;
			T18_ = inet_ntop_LTipcLQ2Q4XlT8sQeiwC8A(((int) (name_2.sin6_family)), ((void*) ((&name_2))), ((NCSTRING) (buf)), ((NI32)chckRange(((NI)sizeof(tyArray_2cWMSJoP9cqN4yIK0ILkQaQ)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!(T18_ == 0)) goto LA19_;
			nimln_(502, "nativesockets.nim");
			T21_ = (NI32)0;
			T21_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T21_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA19_: ;
		nimln_(503, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf))));
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name_2.sin6_port);
	}
	break;
	default:
	{
		nimln_(505, "nativesockets.nim");
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(((NI32) -1), ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(void, getPeerAddr_U7rY6ScGBPOrRGnI22ZKxw_2)(NI socket_0, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result) {
	nimfr_("getPeerAddr", "nativesockets.nim");
	nimln_(511, "nativesockets.nim");
	switch (domain) {
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		SOCKADDR_IN name;
		unsigned int namelen;
		NCSTRING T8_;
		memset((void*)(&name), 0, sizeof(name));
		nimln_(515, "nativesockets.nim");
		name.sin_family = ((NI16) 2);
		nimln_(518, "nativesockets.nim");
		namelen = ((unsigned int) (((NI)sizeof(SOCKADDR_IN))));
		nimln_(519, "nativesockets.nim");
		{
			int T4_;
			NI32 T7_;
			T4_ = (int)0;
			T4_ = Dl_129231_(socket_0, ((SOCKADDR*) ((&name))), (&namelen));
			if (!(T4_ == ((NI32) -1))) goto LA5_;
			nimln_(521, "nativesockets.nim");
			T7_ = (NI32)0;
			T7_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T7_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA5_: ;
		nimln_(522, "nativesockets.nim");
		T8_ = (NCSTRING)0;
		T8_ = Dl_129362_(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(T8_));
		nimln_(523, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name.sin_port);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 23):
	{
		SOCKADDR_IN6 name_2;
		unsigned int namelen_2;
		tyArray_2cWMSJoP9cqN4yIK0ILkQaQ buf;
		memset((void*)(&name_2), 0, sizeof(name_2));
		nimln_(527, "nativesockets.nim");
		name_2.sin6_family = ((NI16) 23);
		nimln_(530, "nativesockets.nim");
		namelen_2 = ((unsigned int) (((NI)sizeof(SOCKADDR_IN6))));
		nimln_(531, "nativesockets.nim");
		{
			int T12_;
			NI32 T15_;
			T12_ = (int)0;
			T12_ = Dl_129231_(socket_0, ((SOCKADDR*) ((&name_2))), (&namelen_2));
			if (!(T12_ == ((NI32) -1))) goto LA13_;
			nimln_(533, "nativesockets.nim");
			T15_ = (NI32)0;
			T15_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA13_: ;
		memset((void*)buf, 0, sizeof(buf));
		nimln_(536, "nativesockets.nim");
		{
			NCSTRING T18_;
			NI32 T21_;
			nimln_(537, "nativesockets.nim");
			T18_ = (NCSTRING)0;
			T18_ = inet_ntop_LTipcLQ2Q4XlT8sQeiwC8A(((int) (name_2.sin6_family)), ((void*) ((&name_2))), ((NCSTRING) (buf)), ((NI32)chckRange(((NI)sizeof(tyArray_2cWMSJoP9cqN4yIK0ILkQaQ)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!(T18_ == 0)) goto LA19_;
			nimln_(538, "nativesockets.nim");
			T21_ = (NI32)0;
			T21_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T21_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
		}
		LA19_: ;
		nimln_(539, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf))));
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name_2.sin6_port);
	}
	break;
	default:
	{
		nimln_(541, "nativesockets.nim");
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(((NI32) -1), ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, getSockOptInt_Bcy79aVO5nZ0AND6B1KoG4g)(NI socket_0, NI level, NI optname) {
	NI result;
	int res;
	unsigned int size;
	nimfr_("getSockOptInt", "nativesockets.nim");
	result = (NI)0;
	res = (int)0;
	nimln_(547, "nativesockets.nim");
	size = ((unsigned int) 4);
	nimln_(548, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_129238_(socket_0, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&res))), (&size));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		nimln_(550, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4_: ;
	nimln_(551, "nativesockets.nim");
	result = ((NI) (res));
	popFrame();
	return result;
}

N_NIMCALL(void, setSockOptInt_Q4lBY4MFWt3Wx9bU5oC8TvA)(NI socket_0, NI level, NI optname, NI optval) {
	int value;
	nimfr_("setSockOptInt", "nativesockets.nim");
	nimln_(556, "nativesockets.nim");
	value = ((int)chckRange(optval, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(557, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_129246_(socket_0, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&value))), ((unsigned int) 4));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		nimln_(559, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4_: ;
	popFrame();
}

N_NIMCALL(void, setBlocking_HDkmwGOArLmNmxp9c5tG9c9cw)(NI s, NIM_BOOL blocking) {
	long mode;
	nimfr_("setBlocking", "nativesockets.nim");
	nimln_(566, "nativesockets.nim");
	mode = ((long) (!(blocking)));
	nimln_(567, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = Dl_165863_(s, ((NI32) -2147195266), (&mode));
		if (!(T3_ == ((NI32) -1))) goto LA4_;
		nimln_(568, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4_: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA, timeValFromMilliseconds_8n6ccdvLo6VgMVggcNy9bzw)(NI timeout) {
	tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA result;
	nimfr_("timeValFromMilliseconds", "nativesockets.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(579, "nativesockets.nim");
	{
		NI seconds;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_13;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_14;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_15;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_16;
		nimln_(378, "system.nim");
		nimln_(579, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(580, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_13 = divInt(timeout, ((NI) 1000));
		seconds = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_13);
		nimln_(581, "nativesockets.nim");
		result.tv_sec = ((NI32)chckRange(seconds, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
		nimln_(582, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_14 = mulInt(seconds, ((NI) 1000));
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_15 = subInt(timeout, (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_14));
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_16 = mulInt((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_15), ((NI) 1000));
		result.tv_usec = ((NI32)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_16), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, createFdSet_Uq0gtMrL5zwaOYtdZK68kg)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd, tySequence_qwqHTkRvwhrRyENtudHQ7g* s, NI* m) {
	nimfr_("createFdSet", "nativesockets.nim");
	nimln_(585, "nativesockets.nim");
	FD_ZERO_yeePfMmq9aNgPmxq9aV4wa4A(fd);
	{
		NI i;
		NI i_2;
		NI L;
		NI T2_;
		i = (NI)0;
		nimln_(3639, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3640, "system.nim");
		T2_ = (s ? s->Sup.len : 0);
		L = T2_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_17;
				if (!(i_2 < L)) goto LA4;
				nimln_(3642, "system.nim");
				if ((NU)(i_2) >= (NU)(s->Sup.len)) raiseIndexError();
				i = s->data[i_2];
				nimln_(587, "nativesockets.nim");
				(*m) = (((*m) >= i) ? (*m) : i);
				nimln_(588, "nativesockets.nim");
				FD_SET_RyfVGaM8zBlYSZOQ5CvEEQ(i, fd);
				nimln_(3643, "system.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_17 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_17);
				nimln_(3644, "system.nim");
				{
					NI T7_;
					T7_ = (s ? s->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_18));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, pruneSocketSet_70Zyypm1k20h9c9bjjAUrOmw)(tySequence_qwqHTkRvwhrRyENtudHQ7g** s, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* fd) {
	NI i;
	NI L;
	NI T1_;
	nimfr_("pruneSocketSet", "nativesockets.nim");
	nimln_(591, "nativesockets.nim");
	i = ((NI) 0);
	nimln_(592, "nativesockets.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	L = T1_;
	{
		nimln_(593, "nativesockets.nim");
		while (1) {
			if (!(i < L)) goto LA3;
			nimln_(594, "nativesockets.nim");
			{
				int T6_;
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_19;
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_20;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				T6_ = (int)0;
				T6_ = FD_ISSET_NkjjeLx4p9b4GT29buKQYcxA((*s)->data[i], fd);
				if (!(T6_ == ((NI32) 0))) goto LA7_;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				nimln_(595, "nativesockets.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_19 = subInt(L, ((NI) 1));
				if ((NU)((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_19)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				(*s)->data[i] = (*s)->data[(NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_19)];
				nimln_(596, "nativesockets.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_20 = subInt(L, ((NI) 1));
				L = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_20);
			}
			goto LA4_;
			LA7_: ;
			{
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_21;
				nimln_(598, "nativesockets.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_21 = addInt(i, ((NI) 1));
				i = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_21);
			}
			LA4_: ;
		} LA3: ;
	}
	nimln_(599, "nativesockets.nim");
	(*s) = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) setLengthSeq(&((*s))->Sup, sizeof(NI), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_NIMCALL(NI, select_eXjloAphe9a2xyF9bVEutDXA)(tySequence_qwqHTkRvwhrRyENtudHQ7g** readfds, NI timeout) {
	NI result;
	tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tv;
	tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog rd;
	NI m;
	nimfr_("select", "nativesockets.nim");
	result = (NI)0;
	nimln_(611, "nativesockets.nim");
	tv = timeValFromMilliseconds_8n6ccdvLo6VgMVggcNy9bzw(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln_(614, "nativesockets.nim");
	m = ((NI) 0);
	nimln_(615, "nativesockets.nim");
	createFdSet_Uq0gtMrL5zwaOYtdZK68kg((&rd), (*readfds), (&m));
	nimln_(617, "nativesockets.nim");
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_22;
		int T5_;
		nimln_(378, "system.nim");
		nimln_(617, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(618, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_22 = addInt(m, ((NI) 1));
		T5_ = (int)0;
		T5_ = Dl_129273_(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_22), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (T5_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_23;
		int T7_;
		nimln_(620, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_23 = addInt(m, ((NI) 1));
		T7_ = (int)0;
		T7_ = Dl_129273_(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_23), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (T7_));
	}
	LA1_: ;
	nimln_(622, "nativesockets.nim");
	pruneSocketSet_70Zyypm1k20h9c9bjjAUrOmw(readfds, (&rd));
	popFrame();
	return result;
}

N_NIMCALL(NI, selectRead_eXjloAphe9a2xyF9bVEutDXA_2)(tySequence_qwqHTkRvwhrRyENtudHQ7g** readfds, NI timeout) {
	NI result;
	tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tv;
	tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog rd;
	NI m;
	nimfr_("selectRead", "nativesockets.nim");
	result = (NI)0;
	nimln_(632, "nativesockets.nim");
	tv = timeValFromMilliseconds_8n6ccdvLo6VgMVggcNy9bzw(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln_(635, "nativesockets.nim");
	m = ((NI) 0);
	nimln_(636, "nativesockets.nim");
	createFdSet_Uq0gtMrL5zwaOYtdZK68kg((&rd), (*readfds), (&m));
	nimln_(638, "nativesockets.nim");
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_24;
		int T5_;
		nimln_(378, "system.nim");
		nimln_(638, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(639, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_24 = addInt(m, ((NI) 1));
		T5_ = (int)0;
		T5_ = Dl_129273_(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_24), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (T5_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_25;
		int T7_;
		nimln_(641, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_25 = addInt(m, ((NI) 1));
		T7_ = (int)0;
		T7_ = Dl_129273_(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_25), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (T7_));
	}
	LA1_: ;
	nimln_(643, "nativesockets.nim");
	pruneSocketSet_70Zyypm1k20h9c9bjjAUrOmw(readfds, (&rd));
	popFrame();
	return result;
}

N_NIMCALL(NI, selectWrite_Xl49alpuj6Qo9brq9cgUHYNlQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g** writefds, NI timeout) {
	NI result;
	tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tv;
	tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog wr;
	NI m;
	nimfr_("selectWrite", "nativesockets.nim");
	result = (NI)0;
	nimln_(654, "nativesockets.nim");
	tv = timeValFromMilliseconds_8n6ccdvLo6VgMVggcNy9bzw(timeout);
	memset((void*)(&wr), 0, sizeof(wr));
	nimln_(657, "nativesockets.nim");
	m = ((NI) 0);
	nimln_(658, "nativesockets.nim");
	createFdSet_Uq0gtMrL5zwaOYtdZK68kg((&wr), (*writefds), (&m));
	nimln_(660, "nativesockets.nim");
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_26;
		int T5_;
		nimln_(378, "system.nim");
		nimln_(660, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(661, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_26 = addInt(m, ((NI) 1));
		T5_ = (int)0;
		T5_ = Dl_129273_(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_26), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, (&tv));
		result = ((NI) (T5_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_27;
		int T7_;
		nimln_(663, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_27 = addInt(m, ((NI) 1));
		T7_ = (int)0;
		T7_ = Dl_129273_(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_27), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, NIM_NIL);
		result = ((NI) (T7_));
	}
	LA1_: ;
	nimln_(665, "nativesockets.nim");
	pruneSocketSet_70Zyypm1k20h9c9bjjAUrOmw(writefds, (&wr));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	nimfr_("nativesockets", "nativesockets.nim");
	nimln_(93, "nativesockets.nim");
	osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w = INVALID_SOCKET;
	nimln_(669, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		nimln_(378, "system.nim");
		nimln_(669, "nativesockets.nim");
		T3_ = (int)0;
		T3_ = Dl_129344_(((NI16) 257), (&wsa_ClAT9bhT9cqG9adztamb5X9b2w));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError_9bdZBDTfBOjOcVVodbA2otw();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA4_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_28[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_29[4] = {
"AF_UNSPEC", 
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_31[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_32[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34[6];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_35[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.size = sizeof(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg);
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.kind = 14;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.base = 0;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30+0].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30+0].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30+0].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_29[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_28[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30+0];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].offset = 0;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].offset = 23;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_28[0];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 1<<2;
NTI_NQT1bItGG2X9byGdrWX7ujw_.size = sizeof(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw);
NTI_NQT1bItGG2X9byGdrWX7ujw_.kind = 14;
NTI_NQT1bItGG2X9byGdrWX7ujw_.base = 0;
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33+5].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33+5].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33+5].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_32[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_31[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33+5];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].offset = 3;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].offset = 5;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_31[0];
NTI_NQT1bItGG2X9byGdrWX7ujw_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9];
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 1<<2;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.size = sizeof(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg);
NTI_dqJ1OqRGclxIMMdSLRzzXg_.kind = 14;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.base = 0;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36 < 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36+10].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36+10].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36+10].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_35[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36+10];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[10].offset = 6;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[11].offset = 17;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[12].offset = 18;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].offset = 19;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].offset = 20;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].offset = 21;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].len = 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34[0];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 1<<2;
if (!((TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2 = nimLoadLibrary((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5);
	Dl_165863_ = (tyProc_awTV7srwWeJ9cGPOCgBQa7g) nimGetProcAddr(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2, "ioctlsocket");
}

