/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\nim-0.17.2\lib -o C:\Users\takala\Desktop\nim\scraping\nimcache\stdlib_winlean.o C:\Users\takala\Desktop\nim\scraping\nimcache\stdlib_winlean.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include "winsock2.h"
#include "ws2tcpip.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_GUID_J2WQBMgezjwf6Trblkflgg tyObject_GUID_J2WQBMgezjwf6Trblkflgg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw;
typedef struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ;
typedef struct tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA;
typedef struct tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw;
typedef struct tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA;
typedef struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog;
typedef struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA;
typedef struct tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NI8 tyArray_9cWG514ToTTjfTPLhXXV0IQ[8];
struct tyObject_GUID_J2WQBMgezjwf6Trblkflgg {
NI32 D1;
NI16 D2;
NI16 D3;
tyArray_9cWG514ToTTjfTPLhXXV0IQ D4;
};
typedef N_STDCALL_PTR(NCSTRING, tyProc_5ctyytqoGFQ0BA1imFGbVw) (int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(void, tyProc_9bc9cLDdaqTE6n5J78feKRYg) (tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw* lpSystemTimeAsFileTime);
struct tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw {
NI32 dwLowDateTime;
NI32 dwHighDateTime;
};
typedef N_STDCALL_PTR(NI32, tyProc_9bXer9a4ps9aSGctILcxWReVw) (void);
typedef N_STDCALL_PTR(NI32, tyProc_aO673xGTLLxou7P7GxoCXA) (NI32 dwFlags, void* lpSource, NI32 dwMessageId, NI32 dwLanguageId, void* lpBuffer, NI32 nSize, void* Arguments);
typedef N_STDCALL_PTR(void, tyProc_im9buRnIvptJfzdASYMEbBA) (void* p);
typedef N_STDCALL_PTR(NI16*, tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA) (void);
typedef N_STDCALL_PTR(NI32, tyProc_hayl9b1HhJokJ1Zo9ctoglPg) (NI16* para1);
typedef N_STDCALL_PTR(NI32, tyProc_IwsYs9blTXXmAlfsBWq604w) (NI16* lpName, NI16* lpValue);
typedef N_STDCALL_PTR(NI, tyProc_9aO2cP4IgwjXF8JfUR57CHQ) (int af, int typ, int protocol);
typedef N_STDCALL_PTR(int, tyProc_IQbFr9cLT9bipWCXYfwYwjOw) (NI s);
typedef N_STDCALL_PTR(int, tyProc_T129bsPZ4FvuSF4rGFSBKkg) (NI s, SOCKADDR* name, unsigned int namelen);
typedef N_STDCALL_PTR(int, tyProc_wy9bpl6t1mtPtDWeg0xLpDA) (NI s, int backlog);
typedef N_STDCALL_PTR(int, tyProc_MvjKU9c5nvs0N3IrS4vNgSw) (NCSTRING nodename, NCSTRING servname, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* hints, tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ** res);
typedef N_STDCALL_PTR(void, tyProc_IV3cwg4tBg3JP8ITSKt7oQ) (tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai);
typedef N_STDCALL_PTR(tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA*, tyProc_E0SwAAX9bj9a9aV7n5MiMKzig) (NCSTRING name, NCSTRING proto);
typedef N_STDCALL_PTR(tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA*, tyProc_M3E1eZF9azJd5WrGSHMqEDA) (int port, NCSTRING proto);
typedef N_STDCALL_PTR(NU32, tyProc_jPIQsVcE09cbsdBUbAUxTCQ) (NCSTRING cp);
typedef N_STDCALL_PTR(tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, tyProc_oU4d9cTB9cxBBS1maSQYgLMA) (IN_ADDR* ip, unsigned int len, int theType);
typedef N_STDCALL_PTR(tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw*, tyProc_sUmKECsDIMWXpmy9a1Mqegg) (NCSTRING name);
typedef N_STDCALL_PTR(int, tyProc_7gdD6mJWQegUjarRikmB9bg) (NCSTRING hostname, int len);
typedef N_STDCALL_PTR(int, tyProc_VXEvL0NvawmzSZzsbIHW6Q) (NI s, SOCKADDR* name, unsigned int* namelen);
typedef N_STDCALL_PTR(NCSTRING, tyProc_MgrHyJlVVXQLRahsT9c14gQ) (IN_ADDR i);
typedef NI16 tyArray_aflWNipJsvDAqOSXjzoiEw[128];
struct tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA {
NI32 dwOSVersionInfoSize;
NI32 dwMajorVersion;
NI32 dwMinorVersion;
NI32 dwBuildNumber;
NI32 dwPlatformId;
tyArray_aflWNipJsvDAqOSXjzoiEw szCSDVersion;
};
typedef N_STDCALL_PTR(NI32, tyProc_pj29cW0AFVn7IRyIuHxtp9bw) (tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA* lpVersionInfo);
typedef NIM_CHAR tyArray_1NlJ8ipZDU6GZ9bDFAyQjfQ[8];
typedef N_STDCALL_PTR(int, tyProc_jT04OBqVwa9aMiCLMGHPMSg) (SOCKADDR* pAddr, NI32 addrSize, void* unused, NCSTRING pBuff, NI32* pBuffSize);
typedef NIM_CHAR tyArray_Wfh9bjgBQ4UqJsyISUuDSuA[16];
typedef N_STDCALL_PTR(void, tyProc_Tjolzh1w2dIIpj3oCDGPFw) (NI32 error);
typedef N_STDCALL_PTR(int, tyProc_smMaEORdTTSo9bCzv0g049aQ) (NI s, int level, int optname, void* optval, unsigned int* optlen);
typedef N_STDCALL_PTR(int, tyProc_K6tJduk9ckQgneh7oD8F4Bg) (NI s, int level, int optname, void* optval, unsigned int optlen);
typedef NI tyArray_SLBTEB08vk46ttuRaTxAYw[64];
struct tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog {
int fd_count;
tyArray_SLBTEB08vk46ttuRaTxAYw fd_array;
};
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_8Py1tJvU9bm83KdBcpIBjeQ) (NI s, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* set);
typedef N_STDCALL_PTR(int, tyProc_rWrG4X5lbcXQyLNkF9aNWhQ) (int nfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* readfds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* writefds, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* exceptfds, tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA* timeout);
typedef N_STDCALL_PTR(int, tyProc_As5z9bYt859cLKWaorPRgQYA) (NI16 wVersionRequired, WSADATA* WSData);
typedef N_STDCALL_PTR(NI, tyProc_dh38EbgnCgluxaqYvYonAg) (NI FileHandle, NI ExistingCompletionPort, NU CompletionKey, NI32 NumberOfConcurrentThreads);
typedef N_STDCALL_PTR(NI32, tyProc_JIaVmlkaszRmqoQwQevY9aA) (NI CompletionPort, NI32* lpNumberOfBytesTransferred, NU* lpCompletionKey, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg** lpOverlapped, NI32 dwMilliseconds);
typedef N_STDCALL_PTR(void, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ) (NI32 para1, NI32 para2, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* para3);
typedef N_STDCALL_PTR(int, tyProc_m8OtNuKklv1X2vQjXQkzSA) (NI s, NI32 dwIoControlCode, void* lpvInBuffer, NI32 cbInBuffer, void* lpvOutBuffer, NI32 cbOutBuffer, NI32* lpcbBytesReturned, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ lpCompletionRoutine);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg {
NI* internal;
NI* internalHigh;
NI32 offset;
NI32 offsetHigh;
NI hEvent;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_STDCALL_PTR(int, tyProc_EzSr684Zq8WJvaKasuLSqQ) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesReceived, NI32* flags, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(int, tyProc_kfyUyr89bETC8vA9b9aJWaMyQ) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesSent, NI32 flags, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(int, tyProc_IaLzHXnYXlJtUwTTdxZCkg) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesSent, NI32 flags, SOCKADDR* name, int namelen, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(int, tyProc_3O4G0IBJdJZ47y0NhcqSGA) (NI s, WSABUF* buf, NI32 bufCount, NI32* bytesReceived, NI32* flags, SOCKADDR* name, int* namelen, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, tyProc_X0Q3cs1Ai9bfe54O0LJQ1fQ completionProc);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_y9bTZn8f8ZZ0xDJI0xhgy9bA) (NI CompletionPort, NI32 dwNumberOfBytesTransferred, NU dwCompletionKey, void* lpOverlapped);
typedef N_STDCALL_PTR(NI, tyProc_uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI32, tyProc_P13srMBg9b3d3yEV9aW4NCoA) (NI WaitHandle);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_f8UTDN69a9cIlDrZoYnegfKw) (NI hEvent);
typedef N_STDCALL_PTR(void, tyProc_D7khg7tG9bCwkkr0wsuurcw) (void* para1, NI32 para2);
typedef N_STDCALL_PTR(NIM_BOOL, tyProc_JxCafHu7hLn8yfng3Vh3tw) (NI* phNewWaitObject, NI hObject, tyProc_D7khg7tG9bCwkkr0wsuurcw Callback, void* Context, NI32 dwMilliseconds, NI32 dwFlags);
typedef N_STDCALL_PTR(int, tyProc_gwfiiqaid9a9cPS02MkvDQZw) (NI s, NI hEventObject, long lNetworkEvents);
struct tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ {
int ai_flags;
int ai_family;
int ai_socktype;
int ai_protocol;
size_t ai_addrlen;
NCSTRING ai_canonname;
SOCKADDR* ai_addr;
tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ* ai_next;
};
typedef NIM_CHAR tyArray_NSMq3FMCIrS8gSbyinBZ8w[14];
typedef N_STDCALL_PTR(NI32, tyProc_I8CYTKrqz0DV8EyysIRhJw) (NI hFile, NI32* lpFileSizeHigh);
typedef N_STDCALL_PTR(NI, tyProc_XIfk9cbRXAfMefSauoFRXLA) (NI16* lpFileName, NI32 dwDesiredAccess, NI32 dwShareMode, void* lpSecurityAttributes, NI32 dwCreationDisposition, NI32 dwFlagsAndAttributes, NI hTemplateFile);
typedef N_STDCALL_PTR(NI32, tyProc_9ajZYMGL5GqiRFqiCC367oA) (NI hFile, void* Buffer, NI32 nNumberOfBytesToRead, NI32* lpNumberOfBytesRead, void* lpOverlapped);
typedef N_STDCALL_PTR(NI32, tyProc_diSZYiv729b4Y9b8LJKB7MkA) (NI hFile, tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg* lpOverlapped, NI32* lpNumberOfBytesTransferred, NI32 bWait);
typedef N_STDCALL_PTR(NI32, tyProc_ZF830CPGZda8saokdzv3Nw) (NI hFile, NI32 lDistanceToMove, NI32* lpDistanceToMoveHigh, NI32 dwMoveMethod);
typedef N_STDCALL_PTR(int, tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) (NI s, void* buf, int len, int flags);
struct tyObject_Servent_uHHxGv5hdkoXDHlVaUxvnA {
NCSTRING s_name;
NCSTRING* s_aliases;
NCSTRING s_proto;
NI16 s_port;
};
struct tyObject_Hostent_s9ci1ibckZ9c2Zr9bnP2iUq9aw {
NCSTRING h_name;
NCSTRING* h_aliases;
NI16 h_addrtype;
NI16 h_length;
NCSTRING* h_addr_list;
};
struct tyObject_Timeval_9boMTr1l3P8e1j9aAjdqsQtA {
NI32 tv_sec;
NI32 tv_usec;
};
typedef NIM_CHAR tyArray_EWK8XzFKXCg2WflN3ijhqA[257];
typedef NIM_CHAR tyArray_4249al09aeC68W9cvqMnjIYOA[129];
N_NIMCALL(void*, loadLib_EFK1MHQsQvQPg5NaJH389bA)(NimStringDesc* path, NIM_BOOL global_symbols);
N_NIMCALL(void*, symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2)(void* lib, NCSTRING name);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, quit_y2WuTG82qH44FHhQsKXOCg)(NimStringDesc* errormsg, NI errorcode) __attribute__((noreturn));
N_STDCALL(NCSTRING, inet_ntop_emulated_NHL7Tp5fr9bGcxCKxCTK3RA)(int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
tyObject_GUID_J2WQBMgezjwf6Trblkflgg WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg;
tyObject_GUID_J2WQBMgezjwf6Trblkflgg WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg;
tyObject_GUID_J2WQBMgezjwf6Trblkflgg WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg;
tyProc_5ctyytqoGFQ0BA1imFGbVw inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw;
void* ws2_hGspZUrVrEMpO9aP9c3dJQPQ;
static void* TM_k6kyf4Co79a84IkK9blFuQVA_5;
tyProc_9bc9cLDdaqTE6n5J78feKRYg Dl_128825_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_9bXer9a4ps9aSGctILcxWReVw Dl_127830_;
tyProc_aO673xGTLLxou7P7GxoCXA Dl_127835_;
tyProc_im9buRnIvptJfzdASYMEbBA Dl_128001_;
tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA Dl_128632_;
tyProc_hayl9b1HhJokJ1Zo9ctoglPg Dl_128634_;
tyProc_IwsYs9blTXXmAlfsBWq604w Dl_128018_;
static void* TM_k6kyf4Co79a84IkK9blFuQVA_23;
tyProc_9aO2cP4IgwjXF8JfUR57CHQ Dl_129197_;
tyProc_IQbFr9cLT9bipWCXYfwYwjOw Dl_129202_;
tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_129212_;
tyProc_wy9bpl6t1mtPtDWeg0xLpDA Dl_129253_;
tyProc_MvjKU9c5nvs0N3IrS4vNgSw Dl_129349_;
tyProc_IV3cwg4tBg3JP8ITSKt7oQ Dl_129358_;
tyProc_E0SwAAX9bj9a9aV7n5MiMKzig Dl_129172_;
tyProc_M3E1eZF9azJd5WrGSHMqEDA Dl_129177_;
tyProc_jPIQsVcE09cbsdBUbAUxTCQ Dl_129311_;
tyProc_oU4d9cTB9cxBBS1maSQYgLMA Dl_129182_;
tyProc_sUmKECsDIMWXpmy9a1Mqegg Dl_129189_;
tyProc_7gdD6mJWQegUjarRikmB9bg Dl_129193_;
tyProc_VXEvL0NvawmzSZzsbIHW6Q Dl_129224_;
tyProc_MgrHyJlVVXQLRahsT9c14gQ Dl_129362_;
tyProc_pj29cW0AFVn7IRyIuHxtp9bw Dl_127524_;
tyProc_jT04OBqVwa9aMiCLMGHPMSg Dl_130028_;
tyProc_Tjolzh1w2dIIpj3oCDGPFw Dl_127832_;
tyProc_VXEvL0NvawmzSZzsbIHW6Q Dl_129231_;
tyProc_smMaEORdTTSo9bCzv0g049aQ Dl_129238_;
tyProc_K6tJduk9ckQgneh7oD8F4Bg Dl_129246_;
tyProc_8Py1tJvU9bm83KdBcpIBjeQ Dl_129314_;
tyProc_rWrG4X5lbcXQyLNkF9aNWhQ Dl_129273_;
tyProc_As5z9bYt859cLKWaorPRgQYA Dl_129344_;
tyProc_dh38EbgnCgluxaqYvYonAg Dl_129866_;
tyProc_JIaVmlkaszRmqoQwQevY9aA Dl_129872_;
tyProc_m8OtNuKklv1X2vQjXQkzSA Dl_129932_;
TNimType NTI_C9agHgxfUtpEDlac6Nu0MCw_;
TNimType NTI_9ayhTq9cybD7eA9aZA09akSNXg_;
extern TNimType NTI_BVbkP29c9aHJK9bePRvpX9bHIQ_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
tyProc_EzSr684Zq8WJvaKasuLSqQ Dl_129947_;
tyProc_kfyUyr89bETC8vA9b9aJWaMyQ Dl_129971_;
tyProc_IaLzHXnYXlJtUwTTdxZCkg Dl_129981_;
tyProc_3O4G0IBJdJZ47y0NhcqSGA Dl_129957_;
tyProc_y9bTZn8f8ZZ0xDJI0xhgy9bA Dl_130320_;
static void* TM_k6kyf4Co79a84IkK9blFuQVA_92;
tyProc_uryidYWkntM7ddjZSyxvyQ Dl_130420_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_130335_;
tyProc_f8UTDN69a9cIlDrZoYnegfKw Dl_130422_;
tyProc_JxCafHu7hLn8yfng3Vh3tw Dl_130326_;
tyProc_gwfiiqaid9a9cPS02MkvDQZw Dl_130415_;
TNimType NTI_C9ahX3gj0cVjII4vjiaSHBQ_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI_xy421WszHaaock9a15gQDRg_;
extern TNimType NTI_S9agCYBinaYZnGWcjTdxclg_;
TNimType NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_;
TNimType NTI_nBU9bsV5o5Xw80pGpGVR8Bw_;
TNimType NTI_9boVVq0W9aThvt3y6X6MODJQ_;
tyProc_hayl9b1HhJokJ1Zo9ctoglPg Dl_128611_;
tyProc_I8CYTKrqz0DV8EyysIRhJw Dl_129611_;
tyProc_XIfk9cbRXAfMefSauoFRXLA Dl_129423_;
tyProc_9ajZYMGL5GqiRFqiCC367oA Dl_127606_;
tyProc_diSZYiv729b4Y9b8LJKB7MkA Dl_129880_;
tyProc_9ajZYMGL5GqiRFqiCC367oA Dl_127614_;
tyProc_ZF830CPGZda8saokdzv3Nw Dl_129604_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_129601_;
tyProc_P13srMBg9b3d3yEV9aW4NCoA Dl_127603_;
tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_129257_;
tyProc_T129bsPZ4FvuSF4rGFSBKkg Dl_129218_;
tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w Dl_129282_;
NIM_CONST tyArray_9cWG514ToTTjfTPLhXXV0IQ TM_k6kyf4Co79a84IkK9blFuQVA_2 = {((NI8) -114),
((NI8) -23),
((NI8) 118),
((NI8) -27),
((NI8) -116),
((NI8) 116),
((NI8) 6),
((NI8) 62)}
;
NIM_CONST tyArray_9cWG514ToTTjfTPLhXXV0IQ TM_k6kyf4Co79a84IkK9blFuQVA_3 = {((NI8) -107),
((NI8) -54),
((NI8) 0),
((NI8) -128),
((NI8) 95),
((NI8) 72),
((NI8) -95),
((NI8) -110)}
;
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_4, "Ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_7, "kernel32", 8);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_8, "kernel32", 8);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_25, "Ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_26, "Ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_57, "Can\'t load inet_ntop proc from Ws2_32.dll", 41);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_94, "ws2_32.dll", 10);
STRING_LITERAL(TM_k6kyf4Co79a84IkK9blFuQVA_95, "ws2_32.dll", 10);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NI64, rdFileTime_8xfVp1z4bc5fRCRgoEFhIQ)(tyObject_FILETIME_bs4NMleDDVF7xsEK0SGLBw f) {
	NI64 result;
	nimfr_("rdFileTime", "winlean.nim");
	result = (NI64)0;
	nimln_(396, "winlean.nim");
	result = (NI64)(((NI64)(NU64)(NU32)(f.dwLowDateTime)) | (NI64)((NU64)(((NI64)(NU64)(NU32)(f.dwHighDateTime))) << (NU64)(((NI) 32))));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_STDCALL(NCSTRING, inet_ntop_emulated_NHL7Tp5fr9bGcxCKxCTK3RA)(int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize) {
	NCSTRING result;
	nimfr_("inet_ntop_emulated", "winlean.nim");
	result = (NCSTRING)0;
	nimln_(888, "winlean.nim");
	switch (family) {
	case ((NI) 2):
	{
		SOCKADDR_IN sa;
		NI32 bs;
		int r;
		memset((void*)(&sa), 0, sizeof(sa));
		nimln_(891, "winlean.nim");
		sa.sin_family = ((NI16) 2);
		nimln_(892, "winlean.nim");
		sa.sin_addr = (*((IN_ADDR*) (paddr)));
		nimln_(893, "winlean.nim");
		bs = stringBufSize;
		nimln_(894, "winlean.nim");
		r = Dl_130028_(((SOCKADDR*) ((&sa))), ((NI32)chckRange(((NI)sizeof(SOCKADDR_IN)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), NIM_NIL, pStringBuffer, (&bs));
		nimln_(895, "winlean.nim");
		{
			nimln_(378, "system.nim");
			nimln_(895, "winlean.nim");
			if (!!((r == ((NI32) 0)))) goto LA4_;
			nimln_(896, "winlean.nim");
			result = NIM_NIL;
		}
		goto LA2_;
		LA4_: ;
		{
			nimln_(898, "winlean.nim");
			result = pStringBuffer;
		}
		LA2_: ;
	}
	break;
	case ((NI) 23):
	{
		SOCKADDR_IN6 sa_2;
		NI32 bs_2;
		int r_2;
		memset((void*)(&sa_2), 0, sizeof(sa_2));
		nimln_(901, "winlean.nim");
		sa_2.sin6_family = ((NI16) 23);
		nimln_(902, "winlean.nim");
		sa_2.sin6_addr = (*((IN6_ADDR*) (paddr)));
		nimln_(903, "winlean.nim");
		bs_2 = stringBufSize;
		nimln_(904, "winlean.nim");
		r_2 = Dl_130028_(((SOCKADDR*) ((&sa_2))), ((NI32)chckRange(((NI)sizeof(SOCKADDR_IN6)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), NIM_NIL, pStringBuffer, (&bs_2));
		nimln_(905, "winlean.nim");
		{
			nimln_(378, "system.nim");
			nimln_(905, "winlean.nim");
			if (!!((r_2 == ((NI32) 0)))) goto LA10_;
			nimln_(906, "winlean.nim");
			result = NIM_NIL;
		}
		goto LA8_;
		LA10_: ;
		{
			nimln_(908, "winlean.nim");
			result = pStringBuffer;
		}
		LA8_: ;
	}
	break;
	default:
	{
		nimln_(910, "winlean.nim");
		Dl_127832_(((NI32) 165));
		nimln_(911, "winlean.nim");
		result = NIM_NIL;
	}
	break;
	}
	popFrame();
	return result;
}

N_STDCALL(NCSTRING, inet_ntop_LTipcLQ2Q4XlT8sQeiwC8A)(int family, void* paddr, NCSTRING pStringBuffer, NI32 stringBufSize) {
	NCSTRING result;
	tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA ver;
	NI32 res;
	nimfr_("inet_ntop", "winlean.nim");
	result = (NCSTRING)0;
	memset((void*)(&ver), 0, sizeof(ver));
	nimln_(916, "winlean.nim");
	ver.dwOSVersionInfoSize = ((NI32)chckRange(((NI)sizeof(tyObject_OSVERSIONINFO_X9bg9adzg6FCyP9bd4JAMb7QA)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	nimln_(917, "winlean.nim");
	res = Dl_127524_((&ver));
	nimln_(918, "winlean.nim");
	{
		if (!(res == ((NI32) 0))) goto LA3_;
		nimln_(919, "winlean.nim");
		result = NIM_NIL;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(920, "winlean.nim");
		if (!(((NI32) 6) <= ver.dwMajorVersion)) goto LA6_;
		nimln_(921, "winlean.nim");
		{
			if (!(inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw == NIM_NIL)) goto LA10_;
			nimln_(922, "winlean.nim");
			quit_y2WuTG82qH44FHhQsKXOCg(((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_57), ((NI) 1));
		}
		LA10_: ;
		nimln_(923, "winlean.nim");
		result = inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw(family, paddr, pStringBuffer, stringBufSize);
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(925, "winlean.nim");
		result = inet_ntop_emulated_NHL7Tp5fr9bGcxCKxCTK3RA(family, paddr, pStringBuffer, stringBufSize);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, FD_ZERO_yeePfMmq9aNgPmxq9aV4wa4A)(tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s) {
	nimfr_("FD_ZERO", "winlean.nim");
	nimln_(626, "winlean.nim");
	(*s).fd_count = ((int) 0);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, FD_SET_RyfVGaM8zBlYSZOQ5CvEEQ)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* s) {
	nimfr_("FD_SET", "winlean.nim");
	nimln_(621, "winlean.nim");
	{
		NI TM_k6kyf4Co79a84IkK9blFuQVA_68;
		if (!((*s).fd_count < ((NI32) 64))) goto LA3_;
		if ((NU)(((NI) ((*s).fd_count))) > (NU)(63)) raiseIndexError();
		nimln_(622, "winlean.nim");
		(*s).fd_array[(((NI) ((*s).fd_count)))- 0] = socket_0;
		nimln_(623, "winlean.nim");
		TM_k6kyf4Co79a84IkK9blFuQVA_68 = addInt((*s).fd_count, ((NI) 1));
		if (TM_k6kyf4Co79a84IkK9blFuQVA_68 < (-2147483647 -1) || TM_k6kyf4Co79a84IkK9blFuQVA_68 > 2147483647) raiseOverflow();
		(*s).fd_count = (int)(TM_k6kyf4Co79a84IkK9blFuQVA_68);
	}
	LA3_: ;
	popFrame();
}

N_NIMCALL(int, FD_ISSET_NkjjeLx4p9b4GT29buKQYcxA)(NI socket_0, tyObject_TFdSet_lYo1mv6gU9aT1ZE1etM9ceog* set) {
	int result;
	nimfr_("FD_ISSET", "winlean.nim");
	result = (int)0;
	nimln_(618, "winlean.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = Dl_129314_(socket_0, set);
		if (!T3_) goto LA4_;
		result = ((NI32) 1);
	}
	goto LA1_;
	LA4_: ;
	{
		result = ((NI32) 0);
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void) {
	tyObject_GUID_J2WQBMgezjwf6Trblkflgg T1_;
	tyObject_GUID_J2WQBMgezjwf6Trblkflgg T2_;
	tyObject_GUID_J2WQBMgezjwf6Trblkflgg T3_;
	nimfr_("winlean", "winlean.nim");
	nimln_(825, "winlean.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.D1 = ((NI32) 631375801);
	T1_.D2 = ((NI16) -8717);
	T1_.D3 = ((NI16) 18016);
	memcpy((void*)T1_.D4, (NIM_CONST void*)TM_k6kyf4Co79a84IkK9blFuQVA_2, sizeof(tyArray_9cWG514ToTTjfTPLhXXV0IQ));
	WSAID_CONNECTEX_YmR9c9crObjjK9ckt1ygsPQKg = T1_;
	nimln_(827, "winlean.nim");
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.D1 = ((NI32) -1254720015);
	T2_.D2 = ((NI16) -13396);
	T2_.D3 = ((NI16) 4559);
	memcpy((void*)T2_.D4, (NIM_CONST void*)TM_k6kyf4Co79a84IkK9blFuQVA_3, sizeof(tyArray_9cWG514ToTTjfTPLhXXV0IQ));
	WSAID_ACCEPTEX_pwoOiDuyZgHBOLaI2GSBpg = T2_;
	nimln_(829, "winlean.nim");
	memset((void*)(&T3_), 0, sizeof(T3_));
	T3_.D1 = ((NI32) -1254720014);
	T3_.D2 = ((NI16) -13396);
	T3_.D3 = ((NI16) 4559);
	memcpy((void*)T3_.D4, (NIM_CONST void*)TM_k6kyf4Co79a84IkK9blFuQVA_3, sizeof(tyArray_9cWG514ToTTjfTPLhXXV0IQ));
	WSAID_GETACCEPTEXSOCKADDRS_rSjtFMq7pCHQR2EQvcKbDg = T3_;
	nimln_(879, "winlean.nim");
	inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw = NIM_NIL;
	nimln_(881, "winlean.nim");
	ws2_hGspZUrVrEMpO9aP9c3dJQPQ = loadLib_EFK1MHQsQvQPg5NaJH389bA(((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_4), NIM_FALSE);
	nimln_(882, "winlean.nim");
	{
		void* T8_;
		nimln_(378, "system.nim");
		nimln_(882, "winlean.nim");
		if (!!((ws2_hGspZUrVrEMpO9aP9c3dJQPQ == NIM_NIL))) goto LA6_;
		nimln_(883, "winlean.nim");
		T8_ = (void*)0;
		T8_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(ws2_hGspZUrVrEMpO9aP9c3dJQPQ, "inet_ntop");
		inet_ntop_real_FVXn9aJ5AOo23ScDsZUc9aZw = ((tyProc_5ctyytqoGFQ0BA1imFGbVw) (T8_));
	}
	LA6_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void) {
static TNimNode* TM_k6kyf4Co79a84IkK9blFuQVA_81[5];
static TNimNode* TM_k6kyf4Co79a84IkK9blFuQVA_106[8];
static TNimNode TM_k6kyf4Co79a84IkK9blFuQVA_0[17];
NTI_C9agHgxfUtpEDlac6Nu0MCw_.size = sizeof(WSABUF);
NTI_C9agHgxfUtpEDlac6Nu0MCw_.kind = 18;
NTI_C9agHgxfUtpEDlac6Nu0MCw_.base = 0;
NTI_C9agHgxfUtpEDlac6Nu0MCw_.flags = 3;
NTI_C9agHgxfUtpEDlac6Nu0MCw_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[0];
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.size = sizeof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg);
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.kind = 18;
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.base = 0;
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.flags = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_81[0] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[2];
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, internal);
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].typ = (&NTI_BVbkP29c9aHJK9bePRvpX9bHIQ_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[2].name = "internal";
TM_k6kyf4Co79a84IkK9blFuQVA_81[1] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[3];
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, internalHigh);
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].typ = (&NTI_BVbkP29c9aHJK9bePRvpX9bHIQ_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[3].name = "internalHigh";
TM_k6kyf4Co79a84IkK9blFuQVA_81[2] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[4];
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, offset);
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[4].name = "offset";
TM_k6kyf4Co79a84IkK9blFuQVA_81[3] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[5];
TM_k6kyf4Co79a84IkK9blFuQVA_0[5].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[5].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, offsetHigh);
TM_k6kyf4Co79a84IkK9blFuQVA_0[5].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[5].name = "offsetHigh";
TM_k6kyf4Co79a84IkK9blFuQVA_81[4] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[6];
TM_k6kyf4Co79a84IkK9blFuQVA_0[6].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[6].offset = offsetof(tyObject_OVERLAPPED_9ayhTq9cybD7eA9aZA09akSNXg, hEvent);
TM_k6kyf4Co79a84IkK9blFuQVA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[6].name = "hEvent";
TM_k6kyf4Co79a84IkK9blFuQVA_0[1].len = 5; TM_k6kyf4Co79a84IkK9blFuQVA_0[1].kind = 2; TM_k6kyf4Co79a84IkK9blFuQVA_0[1].sons = &TM_k6kyf4Co79a84IkK9blFuQVA_81[0];
NTI_9ayhTq9cybD7eA9aZA09akSNXg_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[1];
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.size = sizeof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ);
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.kind = 18;
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.base = 0;
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.flags = 3;
TM_k6kyf4Co79a84IkK9blFuQVA_106[0] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[8];
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_flags);
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[8].name = "ai_flags";
TM_k6kyf4Co79a84IkK9blFuQVA_106[1] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[9];
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_family);
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[9].name = "ai_family";
TM_k6kyf4Co79a84IkK9blFuQVA_106[2] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[10];
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_socktype);
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[10].name = "ai_socktype";
TM_k6kyf4Co79a84IkK9blFuQVA_106[3] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[11];
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_protocol);
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[11].name = "ai_protocol";
TM_k6kyf4Co79a84IkK9blFuQVA_106[4] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[12];
TM_k6kyf4Co79a84IkK9blFuQVA_0[12].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[12].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_addrlen);
TM_k6kyf4Co79a84IkK9blFuQVA_0[12].typ = (&NTI_xy421WszHaaock9a15gQDRg_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[12].name = "ai_addrlen";
TM_k6kyf4Co79a84IkK9blFuQVA_106[5] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[13];
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_canonname);
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].typ = (&NTI_S9agCYBinaYZnGWcjTdxclg_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[13].name = "ai_canonname";
TM_k6kyf4Co79a84IkK9blFuQVA_106[6] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[14];
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.size = sizeof(SOCKADDR);
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.kind = 18;
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.base = 0;
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.flags = 3;
NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[15];
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.size = sizeof(SOCKADDR*);
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.kind = 21;
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.base = (&NTI_iPePZVyyc9cQV6V9cwz9ajG9bg_);
NTI_nBU9bsV5o5Xw80pGpGVR8Bw_.flags = 3;
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_addr);
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].typ = (&NTI_nBU9bsV5o5Xw80pGpGVR8Bw_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[14].name = "ai_addr";
TM_k6kyf4Co79a84IkK9blFuQVA_106[7] = &TM_k6kyf4Co79a84IkK9blFuQVA_0[16];
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].kind = 1;
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].offset = offsetof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ, ai_next);
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].typ = (&NTI_9boVVq0W9aThvt3y6X6MODJQ_);
TM_k6kyf4Co79a84IkK9blFuQVA_0[16].name = "ai_next";
TM_k6kyf4Co79a84IkK9blFuQVA_0[7].len = 8; TM_k6kyf4Co79a84IkK9blFuQVA_0[7].kind = 2; TM_k6kyf4Co79a84IkK9blFuQVA_0[7].sons = &TM_k6kyf4Co79a84IkK9blFuQVA_106[0];
NTI_C9ahX3gj0cVjII4vjiaSHBQ_.node = &TM_k6kyf4Co79a84IkK9blFuQVA_0[7];
NTI_9boVVq0W9aThvt3y6X6MODJQ_.size = sizeof(tyObject_AddrInfo_C9ahX3gj0cVjII4vjiaSHBQ*);
NTI_9boVVq0W9aThvt3y6X6MODJQ_.kind = 21;
NTI_9boVVq0W9aThvt3y6X6MODJQ_.base = (&NTI_C9ahX3gj0cVjII4vjiaSHBQ_);
NTI_9boVVq0W9aThvt3y6X6MODJQ_.flags = 3;
if (!((TM_k6kyf4Co79a84IkK9blFuQVA_5 = nimLoadLibrary((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_7))
)) nimLoadLibraryError((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_8);
	Dl_128825_ = (tyProc_9bc9cLDdaqTE6n5J78feKRYg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetSystemTimeAsFileTime");
	Dl_127830_ = (tyProc_9bXer9a4ps9aSGctILcxWReVw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetLastError");
	Dl_127835_ = (tyProc_aO673xGTLLxou7P7GxoCXA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "FormatMessageW");
	Dl_128001_ = (tyProc_im9buRnIvptJfzdASYMEbBA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "LocalFree");
	Dl_128632_ = (tyProc_9cu0cWy2jNXKVhds9cs4T9a9cA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetEnvironmentStringsW");
	Dl_128634_ = (tyProc_hayl9b1HhJokJ1Zo9ctoglPg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "FreeEnvironmentStringsW");
	Dl_128018_ = (tyProc_IwsYs9blTXXmAlfsBWq604w) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "SetEnvironmentVariableW");
if (!((TM_k6kyf4Co79a84IkK9blFuQVA_23 = nimLoadLibrary((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_25))
)) nimLoadLibraryError((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_26);
	Dl_129197_ = (tyProc_9aO2cP4IgwjXF8JfUR57CHQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "socket");
	Dl_129202_ = (tyProc_IQbFr9cLT9bipWCXYfwYwjOw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "closesocket");
	Dl_129212_ = (tyProc_T129bsPZ4FvuSF4rGFSBKkg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "bind");
	Dl_129253_ = (tyProc_wy9bpl6t1mtPtDWeg0xLpDA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "listen");
	Dl_129349_ = (tyProc_MvjKU9c5nvs0N3IrS4vNgSw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "getaddrinfo");
	Dl_129358_ = (tyProc_IV3cwg4tBg3JP8ITSKt7oQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "freeaddrinfo");
	Dl_129172_ = (tyProc_E0SwAAX9bj9a9aV7n5MiMKzig) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "getservbyname");
	Dl_129177_ = (tyProc_M3E1eZF9azJd5WrGSHMqEDA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "getservbyport");
	Dl_129311_ = (tyProc_jPIQsVcE09cbsdBUbAUxTCQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "inet_addr");
	Dl_129182_ = (tyProc_oU4d9cTB9cxBBS1maSQYgLMA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "gethostbyaddr");
	Dl_129189_ = (tyProc_sUmKECsDIMWXpmy9a1Mqegg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "gethostbyname");
	Dl_129193_ = (tyProc_7gdD6mJWQegUjarRikmB9bg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "gethostname");
	Dl_129224_ = (tyProc_VXEvL0NvawmzSZzsbIHW6Q) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "getsockname");
	Dl_129362_ = (tyProc_MgrHyJlVVXQLRahsT9c14gQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "inet_ntoa");
	Dl_127524_ = (tyProc_pj29cW0AFVn7IRyIuHxtp9bw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetVersionExW");
	Dl_130028_ = (tyProc_jT04OBqVwa9aMiCLMGHPMSg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "WSAAddressToStringA");
	Dl_127832_ = (tyProc_Tjolzh1w2dIIpj3oCDGPFw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "SetLastError");
	Dl_129231_ = (tyProc_VXEvL0NvawmzSZzsbIHW6Q) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "getpeername");
	Dl_129238_ = (tyProc_smMaEORdTTSo9bCzv0g049aQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "getsockopt");
	Dl_129246_ = (tyProc_K6tJduk9ckQgneh7oD8F4Bg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "setsockopt");
	Dl_129314_ = (tyProc_8Py1tJvU9bm83KdBcpIBjeQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "__WSAFDIsSet");
	Dl_129273_ = (tyProc_rWrG4X5lbcXQyLNkF9aNWhQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "select");
	Dl_129344_ = (tyProc_As5z9bYt859cLKWaorPRgQYA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "WSAStartup");
	Dl_129866_ = (tyProc_dh38EbgnCgluxaqYvYonAg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "CreateIoCompletionPort");
	Dl_129872_ = (tyProc_JIaVmlkaszRmqoQwQevY9aA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetQueuedCompletionStatus");
	Dl_129932_ = (tyProc_m8OtNuKklv1X2vQjXQkzSA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "WSAIoctl");
	Dl_129947_ = (tyProc_EzSr684Zq8WJvaKasuLSqQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "WSARecv");
	Dl_129971_ = (tyProc_kfyUyr89bETC8vA9b9aJWaMyQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "WSASend");
	Dl_129981_ = (tyProc_IaLzHXnYXlJtUwTTdxZCkg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "WSASendTo");
	Dl_129957_ = (tyProc_3O4G0IBJdJZ47y0NhcqSGA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "WSARecvFrom");
	Dl_130320_ = (tyProc_y9bTZn8f8ZZ0xDJI0xhgy9bA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "PostQueuedCompletionStatus");
if (!((TM_k6kyf4Co79a84IkK9blFuQVA_92 = nimLoadLibrary((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_94))
)) nimLoadLibraryError((NimStringDesc*) &TM_k6kyf4Co79a84IkK9blFuQVA_95);
	Dl_130420_ = (tyProc_uryidYWkntM7ddjZSyxvyQ) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_92, "WSACreateEvent");
	Dl_130335_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "UnregisterWait");
	Dl_130422_ = (tyProc_f8UTDN69a9cIlDrZoYnegfKw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_92, "WSACloseEvent");
	Dl_130326_ = (tyProc_JxCafHu7hLn8yfng3Vh3tw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "RegisterWaitForSingleObject");
	Dl_130415_ = (tyProc_gwfiiqaid9a9cPS02MkvDQZw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_92, "WSAEventSelect");
	Dl_128611_ = (tyProc_hayl9b1HhJokJ1Zo9ctoglPg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetFileAttributesW");
	Dl_129611_ = (tyProc_I8CYTKrqz0DV8EyysIRhJw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetFileSize");
	Dl_129423_ = (tyProc_XIfk9cbRXAfMefSauoFRXLA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "CreateFileW");
	Dl_127606_ = (tyProc_9ajZYMGL5GqiRFqiCC367oA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "ReadFile");
	Dl_129880_ = (tyProc_diSZYiv729b4Y9b8LJKB7MkA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "GetOverlappedResult");
	Dl_127614_ = (tyProc_9ajZYMGL5GqiRFqiCC367oA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "WriteFile");
	Dl_129604_ = (tyProc_ZF830CPGZda8saokdzv3Nw) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "SetFilePointer");
	Dl_129601_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "SetEndOfFile");
	Dl_127603_ = (tyProc_P13srMBg9b3d3yEV9aW4NCoA) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_5, "CloseHandle");
	Dl_129257_ = (tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "recv");
	Dl_129218_ = (tyProc_T129bsPZ4FvuSF4rGFSBKkg) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "connect");
	Dl_129282_ = (tyProc_4YBDaTH9b4xNNXSV9ahdJZ8w) nimGetProcAddr(TM_k6kyf4Co79a84IkK9blFuQVA_23, "send");
}

