/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\nim-0.17.2\lib -o C:\Users\takala\Desktop\nim\shortest_path\nimcache\shortest_path.o C:\Users\takala\Desktop\nim\shortest_path\nimcache\shortest_path.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg;
typedef struct tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_8EO6J9buz7Wv9btYuiQsugTA tySequence_8EO6J9buz7Wv9btYuiQsugTA;
typedef struct tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg;
typedef struct tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_9adBH3qZW0v24WA4zgvLKQw tySequence_9adBH3qZW0v24WA4zgvLKQw;
typedef struct tyTuple_8uuE9aiNeTntPusa6QK6mrA tyTuple_8uuE9aiNeTntPusa6QK6mrA;
typedef struct tyTuple_0ztpKbiG1WzfKCxsQTaMUA tyTuple_0ztpKbiG1WzfKCxsQTaMUA;
typedef struct NimStringDesc NimStringDesc;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA {
NI from_node_id;
NI to_node_id;
NF cost;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg {
tySequence_8EO6J9buz7Wv9btYuiQsugTA* data;
NI counter;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw {
NI node_id;
NI search_flag;
NI previous_node_id;
NF shortest_length;
tySequence_qwqHTkRvwhrRyENtudHQ7g* out_link_id_list;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg {
tySequence_9adBH3qZW0v24WA4zgvLKQw* data;
NI counter;
};
struct tyTuple_8uuE9aiNeTntPusa6QK6mrA {
NI Field0;
NI Field1;
tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw Field2;
};
struct tyTuple_0ztpKbiG1WzfKCxsQTaMUA {
NI Field0;
NI Field1;
tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA Field2;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_8EO6J9buz7Wv9btYuiQsugTA {
  TGenericSeq Sup;
  tyTuple_0ztpKbiG1WzfKCxsQTaMUA data[SEQ_DECL_SIZE];
};
struct tySequence_9adBH3qZW0v24WA4zgvLKQw {
  TGenericSeq Sup;
  tyTuple_8uuE9aiNeTntPusa6QK6mrA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, initTable_49bcdVMIMbIGY9b2BUBo8gHw)(NI initialSize, tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* Result);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, initTable_esWaQ2WysfWDrPkJSMDUXQ)(NI initialSize, tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* Result);
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op);
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_5)(void);
N_NIMCALL(NIM_BOOL, hasKey_oeO39bsC1Qro3Twq9b21qsOQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key);
static N_INLINE(NI, rawGet_fBRSg0t3gW4ui4taPxPbbAtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI* hc);
static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, X5BX5Deq__8z9aLwqG2SZM5zKb1L6dVXw)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t, NI key, tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* val);
N_NIMCALL(void, enlarge_LsIgz62zlPjiy0vWiKuhbQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t);
N_NIMCALL(void, rawInsert_NlseF0RW9aqxLVwFDObcgsA)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t, tySequence_9adBH3qZW0v24WA4zgvLKQw** data, NI key, tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_6Z39bxi3lyE9cdC9bitF9b9aecQtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI hc);
N_NIMCALL(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw*, X5BX5D__MTtBalJR9cEO6l2rYnmji0A)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t, NI key);
static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgshortest_path)(NI* a, NI aLen_0, NI item);
static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAshortest_path)(NI* a, NI aLen_0, NI item);
N_NIMCALL(void, add_node_data_P5Tjjc4dr0L2N7qMUUt9bzQ)(NI from_node_id, NI to_node_id, NI tr_link_id);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(void, X5BX5Deq__ma9c4EGMEASELhV3hp3OQIg)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t, NI key, tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA* val);
static N_INLINE(NI, rawGet_r3ZmKXPR59cWfnCisuLC8bAtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI* hc);
N_NIMCALL(void, enlarge_RvPhrm9a4MTYVebQzWX5ozQ)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t);
N_NIMCALL(void, rawInsert_nRpgrytJ3Z0tNdacQoWJzg)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t, tySequence_8EO6J9buz7Wv9btYuiQsugTA** data, NI key, tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_l6E9cjo1EKg45r79brFExt9awtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI hc);
N_NIMCALL(NimStringDesc*, dollar__us9cNjelw5Dbj9a9cQ9cvt2Xug)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t);
N_NIMCALL(NI, len_bqmagGU9aQE9bzgd9bmeREAeQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t);
N_NIMCALL(NimStringDesc*, dollar__5UHxuEyludleKobUqdrkaQ)(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* x);
N_NIMCALL(NimStringDesc*, dollar__H9byP9au7Ewl1LWJ70fLKs7Q)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x);
N_NIMCALL(NimStringDesc*, collectionToString_9aCCpFn3xaLLHw6Vu0pZCqQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x, NimStringDesc* b, NimStringDesc* e);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NIM_BOOL, endOfFile_OpxMRqWNQzmofyVQsNQqVA)(FILE* f);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_15)(void);
N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_16)(void);
N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, shortest_pathDatInit000)(void);
TNimType NTI_zs3DqdvyXMR09coxNYhpykA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg link_table_ZZ568sJB9cdOZDLnCLHkoEQ;
extern TNimType NTI_roIcfs5Z7z3HCjEg9cR6XBg_;
TNimType NTI_OhqTobDCYishoYtsWYdJvw_;
TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg node_table_oT672c9a8zHrvLM2iSQ6ACA;
extern TNimType NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
FILE* f_9a5e85lHTFK1oTlaNODSiFg;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
NI line_counter_st8hzHeGC27s12Za5NPH4g;
NI f_node_vgg39bO9bddyDgi1NxsUVuWw;
NI t_node_RSDDWK9a4XQOaHXtAYkLz2Q;
NF c_L29cfXGT69bAo9aT7plV8oyVw;
NimStringDesc* line_CW89aZLyVcJ0A4oaXZJL3fA;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* line_list_ULsdmocJ2Rgb7GzeWOxruQ;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA link_obj_9c2e4a59anAyAmEpc6YCvXNA;
STRING_LITERAL(TM_jiTu3IRx6dXmKvDzLTr9csA_13, "network.dat", 11);
STRING_LITERAL(TM_jiTu3IRx6dXmKvDzLTr9csA_17, "\011", 1);
STRING_LITERAL(TM_jiTu3IRx6dXmKvDzLTr9csA_19, "closed", 6);
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_3)(void) {
	nimGCvisit((void*)link_table_ZZ568sJB9cdOZDLnCLHkoEQ.data, 0);
}
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	a = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_5)(void) {
	nimGCvisit((void*)node_table_oT672c9a8zHrvLM2iSQ6ACA.data, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(109, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(378, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_jiTu3IRx6dXmKvDzLTr9csA_6;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_jiTu3IRx6dXmKvDzLTr9csA_6 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_6) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_fBRSg0t3gW4ui4taPxPbbAtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_jiTu3IRx6dXmKvDzLTr9csA_7;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_jiTu3IRx6dXmKvDzLTr9csA_7 = subInt(((NI) -1), h);
	result = (NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_7);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_6Z39bxi3lyE9cdC9bitF9b9aecQtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_jiTu3IRx6dXmKvDzLTr9csA_8;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_jiTu3IRx6dXmKvDzLTr9csA_8 = subInt(((NI) -1), h);
	result = (NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_8);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAshortest_path)(NI* a, NI aLen_0, NI item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(2078, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2079, "system.nim");
			while (1) {
				NI TM_jiTu3IRx6dXmKvDzLTr9csA_9;
				NI TM_jiTu3IRx6dXmKvDzLTr9csA_10;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2080, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2312, "system.nim");
				{
					if (!(i == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2313, "system.nim");
				TM_jiTu3IRx6dXmKvDzLTr9csA_9 = addInt(result, ((NI) 1));
				result = (NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_9);
				nimln_(2081, "system.nim");
				TM_jiTu3IRx6dXmKvDzLTr9csA_10 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_10);
			} LA3: ;
		}
	}
	nimln_(2314, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgshortest_path)(NI* a, NI aLen_0, NI item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2319, "system.nim");
	T1_ = (NI)0;
	T1_ = find_b2asjP2y9cPDPwOLa1pD5PAshortest_path(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, add_node_data_P5Tjjc4dr0L2N7qMUUt9bzQ)(NI from_node_id, NI to_node_id, NI tr_link_id) {
	nimfr_("add_node_data", "shortest_path.nim");
	nimln_(24, "shortest_path.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasKey_oeO39bsC1Qro3Twq9b21qsOQ(node_table_oT672c9a8zHrvLM2iSQ6ACA, to_node_id);
		if (!T3_) goto LA4_;
	}
	goto LA1_;
	LA4_: ;
	{
		tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw node_obj;
		tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw T7_;
		memset((void*)(&node_obj), 0, sizeof(node_obj));
		nimln_(27, "shortest_path.nim");
		memset((void*)(&T7_), 0, sizeof(T7_));
		memset((void*)(&T7_), 0, sizeof(T7_));
		T7_.node_id = to_node_id;
		T7_.search_flag = ((NI) 0);
		T7_.previous_node_id = ((NI) -1);
		T7_.shortest_length = INF;
		T7_.out_link_id_list = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 0);
		memcpy((void*)(&node_obj), (NIM_CONST void*)(&T7_), sizeof(node_obj));
		nimln_(28, "shortest_path.nim");
		X5BX5Deq__8z9aLwqG2SZM5zKb1L6dVXw((&node_table_oT672c9a8zHrvLM2iSQ6ACA), to_node_id, (&node_obj));
	}
	LA1_: ;
	nimln_(29, "shortest_path.nim");
	{
		NIM_BOOL T10_;
		T10_ = (NIM_BOOL)0;
		T10_ = hasKey_oeO39bsC1Qro3Twq9b21qsOQ(node_table_oT672c9a8zHrvLM2iSQ6ACA, from_node_id);
		if (!T10_) goto LA11_;
		nimln_(30, "shortest_path.nim");
		{
			tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* T15_;
			NIM_BOOL T16_;
			T15_ = (tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw*)0;
			T15_ = X5BX5D__MTtBalJR9cEO6l2rYnmji0A((&node_table_oT672c9a8zHrvLM2iSQ6ACA), from_node_id);
			T16_ = (NIM_BOOL)0;
			T16_ = contains_P6sCVNQ9cdTFh3rtVXMEtxgshortest_path((*T15_).out_link_id_list->data, (*T15_).out_link_id_list->Sup.len, tr_link_id);
			if (!T16_) goto LA17_;
		}
		goto LA13_;
		LA17_: ;
		{
			tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* T20_;
			NI T21_;
			nimln_(33, "shortest_path.nim");
			T20_ = (tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw*)0;
			T20_ = X5BX5D__MTtBalJR9cEO6l2rYnmji0A((&node_table_oT672c9a8zHrvLM2iSQ6ACA), from_node_id);
			(*T20_).out_link_id_list = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) incrSeqV2(&((*T20_).out_link_id_list)->Sup, sizeof(NI));
			T21_ = (*T20_).out_link_id_list->Sup.len++;
			(*T20_).out_link_id_list->data[T21_] = tr_link_id;
		}
		LA13_: ;
	}
	goto LA8_;
	LA11_: ;
	{
		tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw node_obj_2;
		tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw T23_;
		memset((void*)(&node_obj_2), 0, sizeof(node_obj_2));
		nimln_(35, "shortest_path.nim");
		memset((void*)(&T23_), 0, sizeof(T23_));
		memset((void*)(&T23_), 0, sizeof(T23_));
		T23_.node_id = from_node_id;
		T23_.search_flag = ((NI) 0);
		T23_.previous_node_id = ((NI) -1);
		T23_.shortest_length = INF;
		T23_.out_link_id_list = (tySequence_qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTI_qwqHTkRvwhrRyENtudHQ7g_), 1);
		T23_.out_link_id_list->data[0] = tr_link_id;
		memcpy((void*)(&node_obj_2), (NIM_CONST void*)(&T23_), sizeof(node_obj_2));
		nimln_(36, "shortest_path.nim");
		X5BX5Deq__8z9aLwqG2SZM5zKb1L6dVXw((&node_table_oT672c9a8zHrvLM2iSQ6ACA), from_node_id, (&node_obj_2));
	}
	LA8_: ;
	popFrame();
}

static N_INLINE(NI, rawGet_r3ZmKXPR59cWfnCisuLC8bAtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_jiTu3IRx6dXmKvDzLTr9csA_11;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_jiTu3IRx6dXmKvDzLTr9csA_11 = subInt(((NI) -1), h);
	result = (NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_11);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_l6E9cjo1EKg45r79brFExt9awtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_jiTu3IRx6dXmKvDzLTr9csA_12;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_jiTu3IRx6dXmKvDzLTr9csA_12 = subInt(((NI) -1), h);
	result = (NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_12);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_15)(void) {
	nimGCvisit((void*)line_CW89aZLyVcJ0A4oaXZJL3fA, 0);
}
static N_NIMCALL(void, TM_jiTu3IRx6dXmKvDzLTr9csA_16)(void) {
	nimGCvisit((void*)line_list_ULsdmocJ2Rgb7GzeWOxruQ, 0);
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	shortest_pathDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_streamsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("shortest_path", "shortest_path.nim");
nimRegisterGlobalMarker(TM_jiTu3IRx6dXmKvDzLTr9csA_3);
nimRegisterGlobalMarker(TM_jiTu3IRx6dXmKvDzLTr9csA_5);
nimRegisterGlobalMarker(TM_jiTu3IRx6dXmKvDzLTr9csA_15);
nimRegisterGlobalMarker(TM_jiTu3IRx6dXmKvDzLTr9csA_16);
	nimln_(18, "shortest_path.nim");
	chckNil((void*)(&link_table_ZZ568sJB9cdOZDLnCLHkoEQ));
	genericReset((void*)(&link_table_ZZ568sJB9cdOZDLnCLHkoEQ), (&NTI_roIcfs5Z7z3HCjEg9cR6XBg_));
	initTable_49bcdVMIMbIGY9b2BUBo8gHw(((NI) 64), (&link_table_ZZ568sJB9cdOZDLnCLHkoEQ));
	nimln_(19, "shortest_path.nim");
	chckNil((void*)(&node_table_oT672c9a8zHrvLM2iSQ6ACA));
	genericReset((void*)(&node_table_oT672c9a8zHrvLM2iSQ6ACA), (&NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_));
	initTable_esWaQ2WysfWDrPkJSMDUXQ(((NI) 64), (&node_table_oT672c9a8zHrvLM2iSQ6ACA));
	{
		TSafePoint TM_jiTu3IRx6dXmKvDzLTr9csA_14;
		nimln_(41, "shortest_path.nim");
		f_9a5e85lHTFK1oTlaNODSiFg = open_hqzpWQbdA2B8l9a6wwNoP4g(((NimStringDesc*) &TM_jiTu3IRx6dXmKvDzLTr9csA_13), ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
		nimln_(42, "shortest_path.nim");
		pushSafePoint(&TM_jiTu3IRx6dXmKvDzLTr9csA_14);
		TM_jiTu3IRx6dXmKvDzLTr9csA_14.status = setjmp(TM_jiTu3IRx6dXmKvDzLTr9csA_14.context);
		if (TM_jiTu3IRx6dXmKvDzLTr9csA_14.status == 0) {
			NimStringDesc* T7_;
			nimln_(45, "shortest_path.nim");
			line_counter_st8hzHeGC27s12Za5NPH4g = ((NI) 1);
			{
				nimln_(49, "shortest_path.nim");
				while (1) {
					NIM_BOOL T5_;
					tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA T6_;
					NI TM_jiTu3IRx6dXmKvDzLTr9csA_18;
					T5_ = (NIM_BOOL)0;
					T5_ = endOfFile_OpxMRqWNQzmofyVQsNQqVA(f_9a5e85lHTFK1oTlaNODSiFg);
					if (!(T5_ == NIM_FALSE)) goto LA4;
					asgnRefNoCycle((void**) (&line_CW89aZLyVcJ0A4oaXZJL3fA), NIM_NIL);
					nimln_(50, "shortest_path.nim");
					asgnRefNoCycle((void**) (&line_CW89aZLyVcJ0A4oaXZJL3fA), readLine_fPRnXwDTqtynUYGl4OixAg(f_9a5e85lHTFK1oTlaNODSiFg));
					asgnRefNoCycle((void**) (&line_list_ULsdmocJ2Rgb7GzeWOxruQ), NIM_NIL);
					nimln_(51, "shortest_path.nim");
					asgnRefNoCycle((void**) (&line_list_ULsdmocJ2Rgb7GzeWOxruQ), nsuSplitString(line_CW89aZLyVcJ0A4oaXZJL3fA, ((NimStringDesc*) &TM_jiTu3IRx6dXmKvDzLTr9csA_17), ((NI) -1)));
					nimln_(52, "shortest_path.nim");
					if ((NU)(((NI) 0)) >= (NU)(line_list_ULsdmocJ2Rgb7GzeWOxruQ->Sup.len)) raiseIndexError();
					f_node_vgg39bO9bddyDgi1NxsUVuWw = nsuParseInt(line_list_ULsdmocJ2Rgb7GzeWOxruQ->data[((NI) 0)]);
					nimln_(53, "shortest_path.nim");
					if ((NU)(((NI) 1)) >= (NU)(line_list_ULsdmocJ2Rgb7GzeWOxruQ->Sup.len)) raiseIndexError();
					t_node_RSDDWK9a4XQOaHXtAYkLz2Q = nsuParseInt(line_list_ULsdmocJ2Rgb7GzeWOxruQ->data[((NI) 1)]);
					nimln_(54, "shortest_path.nim");
					add_node_data_P5Tjjc4dr0L2N7qMUUt9bzQ(f_node_vgg39bO9bddyDgi1NxsUVuWw, t_node_RSDDWK9a4XQOaHXtAYkLz2Q, line_counter_st8hzHeGC27s12Za5NPH4g);
					nimln_(55, "shortest_path.nim");
					if ((NU)(((NI) 2)) >= (NU)(line_list_ULsdmocJ2Rgb7GzeWOxruQ->Sup.len)) raiseIndexError();
					c_L29cfXGT69bAo9aT7plV8oyVw = nsuParseFloat(line_list_ULsdmocJ2Rgb7GzeWOxruQ->data[((NI) 2)]);
					chckNil((void*)(&link_obj_9c2e4a59anAyAmEpc6YCvXNA));
					genericReset((void*)(&link_obj_9c2e4a59anAyAmEpc6YCvXNA), (&NTI_zs3DqdvyXMR09coxNYhpykA_));
					nimln_(56, "shortest_path.nim");
					memset((void*)(&T6_), 0, sizeof(T6_));
					T6_.from_node_id = f_node_vgg39bO9bddyDgi1NxsUVuWw;
					T6_.to_node_id = t_node_RSDDWK9a4XQOaHXtAYkLz2Q;
					T6_.cost = c_L29cfXGT69bAo9aT7plV8oyVw;
					link_obj_9c2e4a59anAyAmEpc6YCvXNA = T6_;
					nimln_(57, "shortest_path.nim");
					X5BX5Deq__ma9c4EGMEASELhV3hp3OQIg((&link_table_ZZ568sJB9cdOZDLnCLHkoEQ), line_counter_st8hzHeGC27s12Za5NPH4g, (&link_obj_9c2e4a59anAyAmEpc6YCvXNA));
					nimln_(58, "shortest_path.nim");
					TM_jiTu3IRx6dXmKvDzLTr9csA_18 = addInt(line_counter_st8hzHeGC27s12Za5NPH4g, ((NI) 1));
					line_counter_st8hzHeGC27s12Za5NPH4g = (NI)(TM_jiTu3IRx6dXmKvDzLTr9csA_18);
				} LA4: ;
			}
			nimln_(59, "shortest_path.nim");
			T7_ = (NimStringDesc*)0;
			T7_ = dollar__us9cNjelw5Dbj9a9cQ9cvt2Xug(node_table_oT672c9a8zHrvLM2iSQ6ACA);
			printf("%s\015\012", T7_? (T7_)->data:"nil");
			fflush(stdout);
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR_);
		}
		{
			nimln_(43, "shortest_path.nim");
			close_BWnr8V7RERYno9bIdPmw8Hw_2(f_9a5e85lHTFK1oTlaNODSiFg);
			nimln_(44, "shortest_path.nim");
			printf("%s\015\012", ((NimStringDesc*) &TM_jiTu3IRx6dXmKvDzLTr9csA_19)? (((NimStringDesc*) &TM_jiTu3IRx6dXmKvDzLTr9csA_19))->data:"nil");
			fflush(stdout);
		}
		if (TM_jiTu3IRx6dXmKvDzLTr9csA_14.status != 0) reraiseException();
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, shortest_pathDatInit000)(void) {
static TNimNode* TM_jiTu3IRx6dXmKvDzLTr9csA_2[3];
static TNimNode* TM_jiTu3IRx6dXmKvDzLTr9csA_4[5];
static TNimNode TM_jiTu3IRx6dXmKvDzLTr9csA_0[10];
NTI_zs3DqdvyXMR09coxNYhpykA_.size = sizeof(tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA);
NTI_zs3DqdvyXMR09coxNYhpykA_.kind = 18;
NTI_zs3DqdvyXMR09coxNYhpykA_.base = 0;
NTI_zs3DqdvyXMR09coxNYhpykA_.flags = 3;
TM_jiTu3IRx6dXmKvDzLTr9csA_2[0] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[1];
TM_jiTu3IRx6dXmKvDzLTr9csA_0[1].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[1].offset = offsetof(tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA, from_node_id);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[1].name = "from_node_id";
TM_jiTu3IRx6dXmKvDzLTr9csA_2[1] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[2];
TM_jiTu3IRx6dXmKvDzLTr9csA_0[2].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[2].offset = offsetof(tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA, to_node_id);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[2].name = "to_node_id";
TM_jiTu3IRx6dXmKvDzLTr9csA_2[2] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[3];
TM_jiTu3IRx6dXmKvDzLTr9csA_0[3].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[3].offset = offsetof(tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA, cost);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[3].name = "cost";
TM_jiTu3IRx6dXmKvDzLTr9csA_0[0].len = 3; TM_jiTu3IRx6dXmKvDzLTr9csA_0[0].kind = 2; TM_jiTu3IRx6dXmKvDzLTr9csA_0[0].sons = &TM_jiTu3IRx6dXmKvDzLTr9csA_2[0];
NTI_zs3DqdvyXMR09coxNYhpykA_.node = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[0];
NTI_OhqTobDCYishoYtsWYdJvw_.size = sizeof(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw);
NTI_OhqTobDCYishoYtsWYdJvw_.kind = 18;
NTI_OhqTobDCYishoYtsWYdJvw_.base = 0;
NTI_OhqTobDCYishoYtsWYdJvw_.flags = 2;
TM_jiTu3IRx6dXmKvDzLTr9csA_4[0] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[5];
TM_jiTu3IRx6dXmKvDzLTr9csA_0[5].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[5].offset = offsetof(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw, node_id);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[5].name = "node_id";
TM_jiTu3IRx6dXmKvDzLTr9csA_4[1] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[6];
TM_jiTu3IRx6dXmKvDzLTr9csA_0[6].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[6].offset = offsetof(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw, search_flag);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[6].name = "search_flag";
TM_jiTu3IRx6dXmKvDzLTr9csA_4[2] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[7];
TM_jiTu3IRx6dXmKvDzLTr9csA_0[7].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[7].offset = offsetof(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw, previous_node_id);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[7].name = "previous_node_id";
TM_jiTu3IRx6dXmKvDzLTr9csA_4[3] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[8];
TM_jiTu3IRx6dXmKvDzLTr9csA_0[8].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[8].offset = offsetof(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw, shortest_length);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[8].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[8].name = "shortest_length";
TM_jiTu3IRx6dXmKvDzLTr9csA_4[4] = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[9];
NTI_qwqHTkRvwhrRyENtudHQ7g_.size = sizeof(tySequence_qwqHTkRvwhrRyENtudHQ7g*);
NTI_qwqHTkRvwhrRyENtudHQ7g_.kind = 24;
NTI_qwqHTkRvwhrRyENtudHQ7g_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_qwqHTkRvwhrRyENtudHQ7g_.flags = 2;
NTI_qwqHTkRvwhrRyENtudHQ7g_.marker = Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[9].kind = 1;
TM_jiTu3IRx6dXmKvDzLTr9csA_0[9].offset = offsetof(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw, out_link_id_list);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[9].typ = (&NTI_qwqHTkRvwhrRyENtudHQ7g_);
TM_jiTu3IRx6dXmKvDzLTr9csA_0[9].name = "out_link_id_list";
TM_jiTu3IRx6dXmKvDzLTr9csA_0[4].len = 5; TM_jiTu3IRx6dXmKvDzLTr9csA_0[4].kind = 2; TM_jiTu3IRx6dXmKvDzLTr9csA_0[4].sons = &TM_jiTu3IRx6dXmKvDzLTr9csA_4[0];
NTI_OhqTobDCYishoYtsWYdJvw_.node = &TM_jiTu3IRx6dXmKvDzLTr9csA_0[4];
}

