/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\nim\nim-0.17.2\dist\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\nim-0.17.2\lib -o C:\Users\takala\Desktop\nim\shortest_path\nimcache\stdlib_tables.o C:\Users\takala\Desktop\nim\shortest_path\nimcache\stdlib_tables.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg;
typedef struct tySequence_8EO6J9buz7Wv9btYuiQsugTA tySequence_8EO6J9buz7Wv9btYuiQsugTA;
typedef struct tyTuple_0ztpKbiG1WzfKCxsQTaMUA tyTuple_0ztpKbiG1WzfKCxsQTaMUA;
typedef struct tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg;
typedef struct tySequence_9adBH3qZW0v24WA4zgvLKQw tySequence_9adBH3qZW0v24WA4zgvLKQw;
typedef struct tyTuple_8uuE9aiNeTntPusa6QK6mrA tyTuple_8uuE9aiNeTntPusa6QK6mrA;
typedef struct tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg {
tySequence_8EO6J9buz7Wv9btYuiQsugTA* data;
NI counter;
};
struct tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA {
NI from_node_id;
NI to_node_id;
NF cost;
};
struct tyTuple_0ztpKbiG1WzfKCxsQTaMUA {
NI Field0;
NI Field1;
tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA Field2;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg {
tySequence_9adBH3qZW0v24WA4zgvLKQw* data;
NI counter;
};
struct tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw {
NI node_id;
NI search_flag;
NI previous_node_id;
NF shortest_length;
tySequence_qwqHTkRvwhrRyENtudHQ7g* out_link_id_list;
};
struct tyTuple_8uuE9aiNeTntPusa6QK6mrA {
NI Field0;
NI Field1;
tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw Field2;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_8EO6J9buz7Wv9btYuiQsugTA {
  TGenericSeq Sup;
  tyTuple_0ztpKbiG1WzfKCxsQTaMUA data[SEQ_DECL_SIZE];
};
struct tySequence_9adBH3qZW0v24WA4zgvLKQw {
  TGenericSeq Sup;
  tyTuple_8uuE9aiNeTntPusa6QK6mrA data[SEQ_DECL_SIZE];
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count);
N_NIMCALL(NI, nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NIM_BOOL, isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_NIMCALL(void, Marker_tySequence_8EO6J9buz7Wv9btYuiQsugTA)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_9adBH3qZW0v24WA4zgvLKQw)(void* p, NI op);
static N_INLINE(NI, rawGet_fBRSg0t3gW4ui4taPxPbbAtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI* hc);
static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(void, enlarge_LsIgz62zlPjiy0vWiKuhbQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t);
N_NIMCALL(void, rawInsert_NlseF0RW9aqxLVwFDObcgsA)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t, tySequence_9adBH3qZW0v24WA4zgvLKQw** data, NI key, tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_6Z39bxi3lyE9cdC9bitF9b9aecQtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI hc);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NI, rawGet_r3ZmKXPR59cWfnCisuLC8bAtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI* hc);
N_NIMCALL(void, enlarge_RvPhrm9a4MTYVebQzWX5ozQ)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t);
N_NIMCALL(void, rawInsert_nRpgrytJ3Z0tNdacQoWJzg)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t, tySequence_8EO6J9buz7Wv9btYuiQsugTA** data, NI key, tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA* val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_l6E9cjo1EKg45r79brFExt9awtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI hc);
N_NIMCALL(NI, len_bqmagGU9aQE9bzgd9bmeREAeQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, dollar__5UHxuEyludleKobUqdrkaQ)(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* x);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_0ztpKbiG1WzfKCxsQTaMUA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_zs3DqdvyXMR09coxNYhpykA_;
TNimType NTI_8EO6J9buz7Wv9btYuiQsugTA_;
TNimType NTI_roIcfs5Z7z3HCjEg9cR6XBg_;
TNimType NTI_8uuE9aiNeTntPusa6QK6mrA_;
extern TNimType NTI_OhqTobDCYishoYtsWYdJvw_;
TNimType NTI_9adBH3qZW0v24WA4zgvLKQw_;
TNimType NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA_;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_2, "\015\012  counter < length ", 21);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_10, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_21, "key not found: ", 15);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_28, "{:}", 3);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_29, "{", 1);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_30, ", ", 2);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_31, ": ", 2);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_33, "}", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isEmpty", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(15, "tableimpl.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(378, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_3;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_4;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_5;
	nimfr_("mustRehash", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(24, "tableimpl.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_2));
	}
	LA3_: ;
	nimln_(25, "tableimpl.nim");
	T5_ = (NIM_BOOL)0;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_3 = mulInt(length, ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_4 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_3) < (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_4));
	if (T5_) goto LA6_;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_5 = subInt(length, counter);
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_5) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_6;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_6 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_6) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_7;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_8;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_9;
	nimfr_("rightSize", "tables.nim");
	result = (NI)0;
	nimln_(136, "tables.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_7 = mulInt(((NI) (count)), ((NI) 3));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_8 = divInt(((NI) ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_7))), ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_9 = addInt(((NI) ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_8))), ((NI) 4));
	result = nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA(((NI) ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_9))));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_8EO6J9buz7Wv9btYuiQsugTA)(void* p, NI op) {
	tySequence_8EO6J9buz7Wv9btYuiQsugTA* a;
	NI T1_;
	a = (tySequence_8EO6J9buz7Wv9btYuiQsugTA*)p;
	T1_ = (NI)0;
}

N_NIMCALL(void, initTable_49bcdVMIMbIGY9b2BUBo8gHw)(NI initialSize, tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* Result) {
	nimfr_("initTable", "tables.nim");
	nimln_(323, "tables.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_10));
	}
	LA4_: ;
	nimln_(324, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln_(325, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_8EO6J9buz7Wv9btYuiQsugTA*) newSeq((&NTI_8EO6J9buz7Wv9btYuiQsugTA_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}
static N_NIMCALL(void, Marker_tySequence_9adBH3qZW0v24WA4zgvLKQw)(void* p, NI op) {
	tySequence_9adBH3qZW0v24WA4zgvLKQw* a;
	NI T1_;
	a = (tySequence_9adBH3qZW0v24WA4zgvLKQw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2.out_link_id_list, op);
	}
}

N_NIMCALL(void, initTable_esWaQ2WysfWDrPkJSMDUXQ)(NI initialSize, tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* Result) {
	nimfr_("initTable", "tables.nim");
	nimln_(323, "tables.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_10));
	}
	LA4_: ;
	nimln_(324, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln_(325, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_9adBH3qZW0v24WA4zgvLKQw*) newSeq((&NTI_9adBH3qZW0v24WA4zgvLKQw_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(109, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_fBRSg0t3gW4ui4taPxPbbAtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_15;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_15 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_15);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, hasKey_oeO39bsC1Qro3Twq9b21qsOQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	nimfr_("hasKey", "tables.nim");
	result = (NIM_BOOL)0;
	hc = (NI)0;
	nimln_(236, "tables.nim");
	T1_ = (NI)0;
	T1_ = rawGet_fBRSg0t3gW4ui4taPxPbbAtables(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	popFrame();
	return result;
}

N_NIMCALL(void, rawInsert_NlseF0RW9aqxLVwFDObcgsA)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t, tySequence_9adBH3qZW0v24WA4zgvLKQw** data, NI key, tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* val, NI hc, NI h) {
	nimfr_("rawInsert", "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(64, "tableimpl.nim");
	(*data)->data[h].Field1 = key;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(65, "tableimpl.nim");
	genericAssign((void*)(&(*data)->data[h].Field2), (void*)val, (&NTI_OhqTobDCYishoYtsWYdJvw_));
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(66, "tableimpl.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_LsIgz62zlPjiy0vWiKuhbQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t) {
	tySequence_9adBH3qZW0v24WA4zgvLKQw* n;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_16;
	tySequence_9adBH3qZW0v24WA4zgvLKQw* T2_;
	nimfr_("enlarge", "tables.nim");
	n = (tySequence_9adBH3qZW0v24WA4zgvLKQw*)0;
	nimln_(286, "tables.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_4SoG2KRQy3oMm9aUzSLtGrA_16 = mulInt(T1_, ((NI) 2));
	n = (tySequence_9adBH3qZW0v24WA4zgvLKQw*) newSeq((&NTI_9adBH3qZW0v24WA4zgvLKQw_), ((NI)chckRange((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_16), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(287, "tables.nim");
	T2_ = (tySequence_9adBH3qZW0v24WA4zgvLKQw*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(288, "tables.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(1973, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1974, "system.nim");
			while (1) {
				NI eh;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_17;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(1975, "system.nim");
				i = res;
				nimln_(289, "tables.nim");
				if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
				eh = n->data[i].Field0;
				nimln_(290, "tables.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(eh);
					if (!T9_) goto LA10_;
					nimln_(291, "tables.nim");
					nimln_(116, "tables.nim");
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						nimln_(292, "tables.nim");
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							nimln_(293, "tables.nim");
							nimln_(116, "tables.nim");
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					nimln_(294, "tables.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_NlseF0RW9aqxLVwFDObcgsA(t, (&(*t).data), n->data[i].Field1, (&n->data[i].Field2), eh, j);
				}
				LA10_: ;
				nimln_(1976, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_17 = addInt(res, ((NI) 1));
				res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_17);
			} LA6: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, rawGetKnownHC_6Z39bxi3lyE9cdC9bitF9b9aecQtables)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t, NI key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_18;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_18 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_18);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, X5BX5Deq__8z9aLwqG2SZM5zKb1L6dVXw)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t, NI key, tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* val) {
	NI hc;
	NI index;
	nimfr_("[]=", "tables.nim");
	hc = (NI)0;
	nimln_(98, "tableimpl.nim");
	index = rawGet_fBRSg0t3gW4ui4taPxPbbAtables((*t), key, (&hc));
	nimln_(307, "tables.nim");
	{
		nimln_(99, "tableimpl.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		genericAssign((void*)(&(*t).data->data[index].Field2), (void*)val, (&NTI_OhqTobDCYishoYtsWYdJvw_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_19;
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_20;
		nimln_(89, "tableimpl.nim");
		{
			NI T8_;
			NIM_BOOL T9_;
			nimln_(117, "tables.nim");
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			nimln_(90, "tableimpl.nim");
			enlarge_LsIgz62zlPjiy0vWiKuhbQ(t);
			nimln_(91, "tableimpl.nim");
			index = rawGetKnownHC_6Z39bxi3lyE9cdC9bitF9b9aecQtables((*t), key, hc);
		}
		LA10_: ;
		nimln_(92, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_19 = subInt(((NI) -1), index);
		index = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_19);
		nimln_(93, "tableimpl.nim");
		rawInsert_NlseF0RW9aqxLVwFDObcgsA(t, (&(*t).data), key, val, hc, index);
		nimln_(94, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_20 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_20);
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw*, X5BX5D__MTtBalJR9cEO6l2rYnmji0A)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg* t, NI key) {
	tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw* result;
	NI hc;
	NI index;
	nimfr_("[]", "tables.nim");
	result = (tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw*)0;
	hc = (NI)0;
	nimln_(147, "tables.nim");
	index = rawGet_fBRSg0t3gW4ui4taPxPbbAtables((*t), key, (&hc));
	nimln_(170, "tables.nim");
	{
		nimln_(148, "tables.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index].Field2);
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(151, "tables.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(170, "tables.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = nimIntToStr(key);
		T6_ = rawNewString(T7_->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_21));
appendString(T6_, T7_);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(151, "tables.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_r3ZmKXPR59cWfnCisuLC8bAtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_22;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_22 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_22);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawInsert_nRpgrytJ3Z0tNdacQoWJzg)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t, tySequence_8EO6J9buz7Wv9btYuiQsugTA** data, NI key, tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA* val, NI hc, NI h) {
	nimfr_("rawInsert", "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(64, "tableimpl.nim");
	(*data)->data[h].Field1 = key;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(65, "tableimpl.nim");
	(*data)->data[h].Field2 = (*val);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(66, "tableimpl.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_RvPhrm9a4MTYVebQzWX5ozQ)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t) {
	tySequence_8EO6J9buz7Wv9btYuiQsugTA* n;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_23;
	tySequence_8EO6J9buz7Wv9btYuiQsugTA* T2_;
	nimfr_("enlarge", "tables.nim");
	n = (tySequence_8EO6J9buz7Wv9btYuiQsugTA*)0;
	nimln_(286, "tables.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_4SoG2KRQy3oMm9aUzSLtGrA_23 = mulInt(T1_, ((NI) 2));
	n = (tySequence_8EO6J9buz7Wv9btYuiQsugTA*) newSeq((&NTI_8EO6J9buz7Wv9btYuiQsugTA_), ((NI)chckRange((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_23), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(287, "tables.nim");
	T2_ = (tySequence_8EO6J9buz7Wv9btYuiQsugTA*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(288, "tables.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(1973, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1974, "system.nim");
			while (1) {
				NI eh;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_24;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(1975, "system.nim");
				i = res;
				nimln_(289, "tables.nim");
				if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
				eh = n->data[i].Field0;
				nimln_(290, "tables.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(eh);
					if (!T9_) goto LA10_;
					nimln_(291, "tables.nim");
					nimln_(116, "tables.nim");
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						nimln_(292, "tables.nim");
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							nimln_(293, "tables.nim");
							nimln_(116, "tables.nim");
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					nimln_(294, "tables.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_nRpgrytJ3Z0tNdacQoWJzg(t, (&(*t).data), n->data[i].Field1, (&n->data[i].Field2), eh, j);
				}
				LA10_: ;
				nimln_(1976, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_24 = addInt(res, ((NI) 1));
				res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_24);
			} LA6: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, rawGetKnownHC_l6E9cjo1EKg45r79brFExt9awtables)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg t, NI key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_25;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_25 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_25);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, X5BX5Deq__ma9c4EGMEASELhV3hp3OQIg)(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg* t, NI key, tyObject_Link_obj_zs3DqdvyXMR09coxNYhpykA* val) {
	NI hc;
	NI index;
	nimfr_("[]=", "tables.nim");
	hc = (NI)0;
	nimln_(98, "tableimpl.nim");
	index = rawGet_r3ZmKXPR59cWfnCisuLC8bAtables((*t), key, (&hc));
	nimln_(307, "tables.nim");
	{
		nimln_(99, "tableimpl.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2 = (*val);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_26;
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_27;
		nimln_(89, "tableimpl.nim");
		{
			NI T8_;
			NIM_BOOL T9_;
			nimln_(117, "tables.nim");
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			nimln_(90, "tableimpl.nim");
			enlarge_RvPhrm9a4MTYVebQzWX5ozQ(t);
			nimln_(91, "tableimpl.nim");
			index = rawGetKnownHC_l6E9cjo1EKg45r79brFExt9awtables((*t), key, hc);
		}
		LA10_: ;
		nimln_(92, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_26 = subInt(((NI) -1), index);
		index = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_26);
		nimln_(93, "tableimpl.nim");
		rawInsert_nRpgrytJ3Z0tNdacQoWJzg(t, (&(*t).data), key, val, hc, index);
		nimln_(94, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_27 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_27);
	}
	LA1_: ;
	popFrame();
}

N_NIMCALL(NI, len_bqmagGU9aQE9bzgd9bmeREAeQ)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t) {
	NI result;
	nimfr_("len", "tables.nim");
	result = (NI)0;
	nimln_(140, "tables.nim");
	result = t.counter;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, dollar__us9cNjelw5Dbj9a9cQ9cvt2Xug)(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg t) {
	NimStringDesc* result;
	nimfr_("$", "tables.nim");
	result = (NimStringDesc*)0;
	nimln_(347, "tables.nim");
	{
		NI T3_;
		nimln_(334, "tables.nim");
		T3_ = (NI)0;
		T3_ = len_bqmagGU9aQE9bzgd9bmeREAeQ(t);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(335, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_28));
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(337, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_29));
		{
			NI key;
			tyObject_Node_obj_OhqTobDCYishoYtsWYdJvw val;
			key = (NI)0;
			memset((void*)(&val), 0, sizeof(val));
			{
				NI h;
				NI colontmp_;
				NI T9_;
				NI res;
				h = (NI)0;
				colontmp_ = (NI)0;
				nimln_(244, "tables.nim");
				T9_ = (t.data ? (t.data->Sup.len-1) : -1);
				colontmp_ = T9_;
				nimln_(1986, "system.nim");
				res = ((NI) 0);
				{
					nimln_(1987, "system.nim");
					while (1) {
						NI TM_4SoG2KRQy3oMm9aUzSLtGrA_32;
						if (!(res <= colontmp_)) goto LA11;
						nimln_(1988, "system.nim");
						h = res;
						nimln_(245, "tables.nim");
						{
							NIM_BOOL T14_;
							NimStringDesc* T21_;
							NimStringDesc* T22_;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							T14_ = (NIM_BOOL)0;
							T14_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
							if (!T14_) goto LA15_;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							key = t.data->data[h].Field1;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							memcpy((void*)(&val), (NIM_CONST void*)(&t.data->data[h].Field2), sizeof(val));
							nimln_(339, "tables.nim");
							{
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA19_;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_30));
							}
							LA19_: ;
							nimln_(340, "tables.nim");
							T21_ = (NimStringDesc*)0;
							T21_ = nimIntToStr(key);
							result = resizeString(result, T21_->Sup.len + 0);
appendString(result, T21_);
							nimln_(341, "tables.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_31));
							nimln_(342, "tables.nim");
							T22_ = (NimStringDesc*)0;
							T22_ = dollar__5UHxuEyludleKobUqdrkaQ((&val));
							result = resizeString(result, T22_->Sup.len + 0);
appendString(result, T22_);
						}
						LA15_: ;
						nimln_(1989, "system.nim");
						TM_4SoG2KRQy3oMm9aUzSLtGrA_32 = addInt(res, ((NI) 1));
						res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_32);
					} LA11: ;
				}
			}
		}
		nimln_(343, "tables.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_33));
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr_("tables", "tables.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_11[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_12[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_13[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_14[2];
static TNimNode TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14];
NTI_0ztpKbiG1WzfKCxsQTaMUA_.size = sizeof(tyTuple_0ztpKbiG1WzfKCxsQTaMUA);
NTI_0ztpKbiG1WzfKCxsQTaMUA_.kind = 18;
NTI_0ztpKbiG1WzfKCxsQTaMUA_.base = 0;
NTI_0ztpKbiG1WzfKCxsQTaMUA_.flags = 3;
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(tyTuple_0ztpKbiG1WzfKCxsQTaMUA, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].offset = offsetof(tyTuple_0ztpKbiG1WzfKCxsQTaMUA, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_11[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(tyTuple_0ztpKbiG1WzfKCxsQTaMUA, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_zs3DqdvyXMR09coxNYhpykA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_11[0];
NTI_0ztpKbiG1WzfKCxsQTaMUA_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
NTI_8EO6J9buz7Wv9btYuiQsugTA_.size = sizeof(tySequence_8EO6J9buz7Wv9btYuiQsugTA*);
NTI_8EO6J9buz7Wv9btYuiQsugTA_.kind = 24;
NTI_8EO6J9buz7Wv9btYuiQsugTA_.base = (&NTI_0ztpKbiG1WzfKCxsQTaMUA_);
NTI_8EO6J9buz7Wv9btYuiQsugTA_.flags = 2;
NTI_8EO6J9buz7Wv9btYuiQsugTA_.marker = Marker_tySequence_8EO6J9buz7Wv9btYuiQsugTA;
NTI_roIcfs5Z7z3HCjEg9cR6XBg_.size = sizeof(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg);
NTI_roIcfs5Z7z3HCjEg9cR6XBg_.kind = 18;
NTI_roIcfs5Z7z3HCjEg9cR6XBg_.base = 0;
NTI_roIcfs5Z7z3HCjEg9cR6XBg_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_12[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_8EO6J9buz7Wv9btYuiQsugTA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_12[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(tyObject_Table_roIcfs5Z7z3HCjEg9cR6XBg, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_12[0];
NTI_roIcfs5Z7z3HCjEg9cR6XBg_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
NTI_8uuE9aiNeTntPusa6QK6mrA_.size = sizeof(tyTuple_8uuE9aiNeTntPusa6QK6mrA);
NTI_8uuE9aiNeTntPusa6QK6mrA_.kind = 18;
NTI_8uuE9aiNeTntPusa6QK6mrA_.base = 0;
NTI_8uuE9aiNeTntPusa6QK6mrA_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_13[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].offset = offsetof(tyTuple_8uuE9aiNeTntPusa6QK6mrA, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_13[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].offset = offsetof(tyTuple_8uuE9aiNeTntPusa6QK6mrA, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_13[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].offset = offsetof(tyTuple_8uuE9aiNeTntPusa6QK6mrA, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].typ = (&NTI_OhqTobDCYishoYtsWYdJvw_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_13[0];
NTI_8uuE9aiNeTntPusa6QK6mrA_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
NTI_9adBH3qZW0v24WA4zgvLKQw_.size = sizeof(tySequence_9adBH3qZW0v24WA4zgvLKQw*);
NTI_9adBH3qZW0v24WA4zgvLKQw_.kind = 24;
NTI_9adBH3qZW0v24WA4zgvLKQw_.base = (&NTI_8uuE9aiNeTntPusa6QK6mrA_);
NTI_9adBH3qZW0v24WA4zgvLKQw_.flags = 2;
NTI_9adBH3qZW0v24WA4zgvLKQw_.marker = Marker_tySequence_9adBH3qZW0v24WA4zgvLKQw;
NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_.size = sizeof(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg);
NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_.kind = 18;
NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_.base = 0;
NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_14[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].offset = offsetof(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].typ = (&NTI_9adBH3qZW0v24WA4zgvLKQw_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_14[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].offset = offsetof(tyObject_Table_maa5vib9c9bWSp9a9cgxVM9aAbg, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_14[0];
NTI_maa5vib9c9bWSp9a9cgxVM9aAbg_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11];
}

